numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch8/v8_batch8_0_0_cfg.json
Loading file ../data/v8_batch8/v8_batch8_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py
Importing netParams from ../data/v8_batch8/v8_batch8_netParams.py

Start time:  2025-08-06 06:58:59.955766

Creating network of 210 cell populations on 128 hosts...
  Number of cells on node 86: 263 
  Number of cells on node 79: 263 
  Number of cells on node 87: 263 
  Number of cells on node 73: 264 
  Number of cells on node 89: 263 
  Number of cells on node 90: 263 
  Number of cells on node 91: 263 
  Number of cells on node 54: 264 
  Number of cells on node 88: 263 
  Number of cells on node 92: 263 
  Number of cells on node 96: 263 
  Number of cells on node 124: 263 
  Number of cells on node 94: 263 
  Number of cells on node 97: 263 
  Number of cells on node 93: 263 
  Number of cells on node 98: 263 
  Number of cells on node 102: 263 
  Number of cells on node 100: 263 
  Number of cells on node 101: 263 
  Number of cells on node 104: 263 
  Number of cells on node 106: 263 
  Number of cells on node 103: 263 
  Number of cells on node 105: 263 
  Number of cells on node 107: 263 
  Number of cells on node 109: 263 
  Number of cells on node 108: 263 
  Number of cells on node 99: 263 
  Number of cells on node 111: 263 
  Number of cells on node 114: 263 
  Number of cells on node 110: 263 
  Number of cells on node 115: 263 
  Number of cells on node 112: 263 
  Number of cells on node 116: 263 
  Number of cells on node 118: 263 
  Number of cells on node 120: 263 
  Number of cells on node 113: 263 
  Number of cells on node 121: 263 
  Number of cells on node 70: 264 
  Number of cells on node 122: 263 
  Number of cells on node 0: 264 
  Number of cells on node 95: 263 
  Number of cells on node 119: 263 
  Number of cells on node 117: 263 
  Number of cells on node 123: 263 
  Number of cells on node 125: 263 
  Number of cells on node 1: 264 
  Number of cells on node 85: 263 
  Number of cells on node 41: 264 
  Number of cells on node 4: 264 
  Number of cells on node 34: 264 
  Number of cells on node 7: 264 
  Number of cells on node 3: 264 
  Number of cells on node 8: 264 
  Number of cells on node 126: 263 
  Number of cells on node 9: 264 
  Number of cells on node 6: 264 
  Number of cells on node 10: 264 
  Number of cells on node 11: 264 
  Number of cells on node 12: 264 
  Number of cells on node 13: 264 
  Number of cells on node 16: 264 
  Number of cells on node 18: 264 
  Number of cells on node 2: 264 
  Number of cells on node 19: 264 
  Number of cells on node 20: 264 
  Number of cells on node 17: 264 
  Number of cells on node 22: 264 
  Number of cells on node 21: 264 
  Number of cells on node 25: 264 
  Number of cells on node 26: 264 
  Number of cells on node 27: 264 
  Number of cells on node 28: 264 
  Number of cells on node 5: 264 
  Number of cells on node 23: 264 
  Number of cells on node 29: 264 
  Number of cells on node 32: 264 
  Number of cells on node 31: 264 
  Number of cells on node 33: 264 
  Number of cells on node 15: 264 
  Number of cells on node 36: 264 
  Number of cells on node 24: 264 
  Number of cells on node 37: 264 
  Number of cells on node 39: 264 
  Number of cells on node 35: 264 
  Number of cells on node 127: 263 
  Number of cells on node 40: 264 
  Number of cells on node 42: 264 
  Number of cells on node 44: 264 
  Number of cells on node 38: 264 
  Number of cells on node 45: 264 
  Number of cells on node 46: 264 
  Number of cells on node 47: 264 
  Number of cells on node 49: 264 
  Number of cells on node 50: 264 
  Number of cells on node 52: 264 
  Number of cells on node 14: 264 
  Number of cells on node 51: 264 
  Number of cells on node 55: 264 
  Number of cells on node 48: 264 
  Number of cells on node 56: 264 
  Number of cells on node 58: 264 
  Number of cells on node 43: 264 
  Number of cells on node 53: 264 
  Number of cells on node 30: 264 
  Number of cells on node 59: 264 
  Number of cells on node 63: 264 
  Number of cells on node 64: 264 
  Number of cells on node 65: 264 
  Number of cells on node 66: 264 
  Number of cells on node 60: 264 
  Number of cells on node 67: 264 
  Number of cells on node 68: 264 
  Number of cells on node 69: 264 
  Number of cells on node 71: 264 
  Number of cells on node 72: 264 
  Number of cells on node 61: 264 
  Number of cells on node 57: 264 
  Number of cells on node 74: 263 
  Number of cells on node 76: 263 
  Number of cells on node 62: 264 
  Number of cells on node 75: 263 
  Number of cells on node 78: 263 
  Number of cells on node 80: 263 
  Number of cells on node 81: 263 
  Number of cells on node 77: 263 
  Number of cells on node 82: 263 
  Number of cells on node 83: 263 
  Number of cells on node 84: 263 
  Done; cell creation time = 16.80 s.
Making connections...
  Number of connections on node 52: 71266 
  Number of synaptic contacts on node 52: 373723 
  Number of connections on node 36: 71515 
  Number of synaptic contacts on node 36: 373158 
  Number of connections on node 20: 73122 
  Number of synaptic contacts on node 20: 384321 
  Number of connections on node 4: 68940 
  Number of synaptic contacts on node 4: 362708 
  Number of connections on node 48: 70648 
  Number of synaptic contacts on node 48: 369839 
  Number of connections on node 40: 70216 
  Number of synaptic contacts on node 40: 368218 
  Number of connections on node 46: 70301 
  Number of synaptic contacts on node 46: 369833 
  Number of connections on node 26: 71061 
  Number of synaptic contacts on node 26: 374173 
  Number of connections on node 0: 69265 
  Number of synaptic contacts on node 0: 361459 
  Number of connections on node 22: 71379 
  Number of synaptic contacts on node 22: 374601 
  Number of connections on node 56: 69494 
  Number of synaptic contacts on node 56: 362133 
  Number of connections on node 12: 69815 
  Number of synaptic contacts on node 12: 367326 
  Number of connections on node 44: 70994 
  Number of synaptic contacts on node 44: 371309 
  Number of connections on node 16: 70576 
  Number of synaptic contacts on node 16: 370607 
  Number of connections on node 60: 70060 
  Number of synaptic contacts on node 60: 364909 
  Number of connections on node 8: 70512 
  Number of synaptic contacts on node 8: 371125 
  Number of connections on node 24: 71902 
  Number of synaptic contacts on node 24: 379497 
  Number of connections on node 32: 68854 
  Number of synaptic contacts on node 32: 361168 
  Number of connections on node 18: 68982 
  Number of synaptic contacts on node 18: 361269 
  Number of connections on node 28: 72007 
  Number of synaptic contacts on node 28: 375397 
  Number of connections on node 14: 69940 
  Number of synaptic contacts on node 14: 369412 
  Number of connections on node 38: 70901 
  Number of synaptic contacts on node 38: 371982 
  Number of connections on node 2: 70050 
  Number of synaptic contacts on node 2: 367593 
  Number of connections on node 30: 67150 
  Number of synaptic contacts on node 30: 354692 
  Number of connections on node 50: 69869 
  Number of synaptic contacts on node 50: 364065 
  Number of connections on node 6: 70865 
  Number of synaptic contacts on node 6: 372193 
  Number of connections on node 54: 70382 
  Number of synaptic contacts on node 54: 368791 
  Number of connections on node 62: 70409 
  Number of synaptic contacts on node 62: 369488 
  Number of connections on node 10: 72195 
  Number of synaptic contacts on node 10: 377495 
  Number of connections on node 58: 70659 
  Number of synaptic contacts on node 58: 369924 
  Number of connections on node 34: 69631 
  Number of synaptic contacts on node 34: 364064 
  Number of connections on node 42: 71540 
  Number of synaptic contacts on node 42: 375228 
  Number of connections on node 84: 68403 
  Number of synaptic contacts on node 84: 359147 
  Number of connections on node 47: 70395 
  Number of synaptic contacts on node 47: 367665 
  Number of connections on node 96: 70628 
  Number of synaptic contacts on node 96: 368998 
  Number of connections on node 82: 69789 
  Number of synaptic contacts on node 82: 364601 
  Number of connections on node 64: 69754 
  Number of synaptic contacts on node 64: 366550 
  Number of connections on node 74: 69947 
  Number of synaptic contacts on node 74: 366715 
  Number of connections on node 122: 69212 
  Number of synaptic contacts on node 122: 362627 
  Number of connections on node 39: 69069 
  Number of synaptic contacts on node 39: 361247 
  Number of connections on node 80: 70152 
  Number of synaptic contacts on node 80: 369155 
  Number of connections on node 78: 71776 
  Number of synaptic contacts on node 78: 376635 
  Number of connections on node 45: 71127 
  Number of synaptic contacts on node 45: 371665 
  Number of connections on node 124: 71995 
  Number of synaptic contacts on node 124: 377566 
  Number of connections on node 53: 71520 
  Number of synaptic contacts on node 53: 372315 
  Number of connections on node 41: 71156 
  Number of synaptic contacts on node 41: 371918 
  Number of connections on node 3: 68250 
  Number of synaptic contacts on node 3: 358286 
  Number of connections on node 68: 70271 
  Number of synaptic contacts on node 68: 363728 
  Number of connections on node 94: 69035 
  Number of synaptic contacts on node 94: 359929 
  Number of connections on node 90: 70771 
  Number of synaptic contacts on node 90: 369800 
  Number of connections on node 66: 70549 
  Number of synaptic contacts on node 66: 367942 
  Number of connections on node 43: 70461 
  Number of synaptic contacts on node 43: 369353 
  Number of connections on node 15: 71396 
  Number of synaptic contacts on node 15: 375655 
  Number of connections on node 116: 70197 
  Number of synaptic contacts on node 116: 368007 
  Number of connections on node 7: 68364 
  Number of synaptic contacts on node 7: 357380 
  Number of connections on node 100: 70209 
  Number of synaptic contacts on node 100: 366233 
  Number of connections on node 114: 69475 
  Number of synaptic contacts on node 114: 360708 
  Number of connections on node 51: 71235 
  Number of synaptic contacts on node 51: 371383 
  Number of connections on node 112: 70585 
  Number of synaptic contacts on node 112: 369039 
  Number of connections on node 102: 69493 
  Number of synaptic contacts on node 102: 364668 
  Number of connections on node 19: 70289 
  Number of synaptic contacts on node 19: 370775 
  Number of connections on node 35: 70673 
  Number of synaptic contacts on node 35: 366751 
  Number of connections on node 118: 69938 
  Number of synaptic contacts on node 118: 369532 
  Number of connections on node 88: 70450 
  Number of synaptic contacts on node 88: 370439 
  Number of connections on node 70: 68485 
  Number of synaptic contacts on node 70: 358077 
  Number of connections on node 126: 70790 
  Number of synaptic contacts on node 126: 373930 
  Number of connections on node 49: 69595 
  Number of synaptic contacts on node 49: 365857 
  Number of connections on node 110: 69592 
  Number of synaptic contacts on node 110: 365253 
  Number of connections on node 86: 67910 
  Number of synaptic contacts on node 86: 356184 
  Number of connections on node 106: 68908 
  Number of synaptic contacts on node 106: 359507 
  Number of connections on node 55: 70020 
  Number of synaptic contacts on node 55: 367286 
  Number of connections on node 37: 70848 
  Number of synaptic contacts on node 37: 368344 
  Number of connections on node 104: 70842 
  Number of synaptic contacts on node 104: 370263 
  Number of connections on node 13: 68467 
  Number of synaptic contacts on node 13: 359150 
  Number of connections on node 76: 71515 
  Number of synaptic contacts on node 76: 373599 
  Number of connections on node 72: 71256 
  Number of synaptic contacts on node 72: 372688 
  Number of connections on node 1: 67398 
  Number of synaptic contacts on node 1: 352405 
  Number of connections on node 120: 70758 
  Number of synaptic contacts on node 120: 369959 
  Number of connections on node 27: 71615 
  Number of synaptic contacts on node 27: 373673 
  Number of connections on node 17: 71678 
  Number of synaptic contacts on node 17: 378338 
  Number of connections on node 108: 70188 
  Number of synaptic contacts on node 108: 366662 
  Number of connections on node 33: 70602 
  Number of synaptic contacts on node 33: 367220 
  Number of connections on node 31: 70137 
  Number of synaptic contacts on node 31: 371097 
  Number of connections on node 59: 71132 
  Number of synaptic contacts on node 59: 372339 
  Number of connections on node 92: 69608 
  Number of synaptic contacts on node 92: 364866 
  Number of connections on node 9: 70451 
  Number of synaptic contacts on node 9: 371271 
  Number of connections on node 25: 70818 
  Number of synaptic contacts on node 25: 372285 
  Number of connections on node 29: 71931 
  Number of synaptic contacts on node 29: 375988 
  Number of connections on node 11: 70023 
  Number of synaptic contacts on node 11: 366754 
  Number of connections on node 21: 70148 
  Number of synaptic contacts on node 21: 368922 
  Number of connections on node 57: 71009 
  Number of synaptic contacts on node 57: 370993 
  Number of connections on node 98: 70375 
  Number of synaptic contacts on node 98: 368906 
  Number of connections on node 5: 69242 
  Number of synaptic contacts on node 5: 362216 
  Number of connections on node 79: 69003 
  Number of synaptic contacts on node 79: 362148 
  Number of connections on node 95: 69628 
  Number of synaptic contacts on node 95: 364884 
  Number of connections on node 23: 71154 
  Number of synaptic contacts on node 23: 376553 
  Number of connections on node 91: 71780 
  Number of synaptic contacts on node 91: 376513 
  Number of connections on node 111: 70705 
  Number of synaptic contacts on node 111: 368768 
  Number of connections on node 61: 68484 
  Number of synaptic contacts on node 61: 358971 
  Number of connections on node 103: 70410 
  Number of synaptic contacts on node 103: 368215 
  Number of connections on node 83: 70072 
  Number of synaptic contacts on node 83: 367184 
  Number of connections on node 123: 70461 
  Number of synaptic contacts on node 123: 370491 
  Number of connections on node 105: 70411 
  Number of synaptic contacts on node 105: 368799 
  Number of connections on node 119: 69776 
  Number of synaptic contacts on node 119: 365950 
  Number of connections on node 65: 68968 
  Number of synaptic contacts on node 65: 361183 
  Number of connections on node 107: 70066 
  Number of synaptic contacts on node 107: 365826 
  Number of connections on node 69: 71908 
  Number of synaptic contacts on node 69: 377123 
  Number of connections on node 115: 69401 
  Number of synaptic contacts on node 115: 362026 
  Number of connections on node 113: 70423 
  Number of synaptic contacts on node 113: 368961 
  Number of connections on node 89: 70299 
  Number of synaptic contacts on node 89: 370181 
  Number of connections on node 73: 70688 
  Number of synaptic contacts on node 73: 371729 
  Number of connections on node 127: 71660 
  Number of synaptic contacts on node 127: 373970 
  Number of connections on node 85: 68603 
  Number of synaptic contacts on node 85: 359846 
  Number of connections on node 97: 71714 
  Number of synaptic contacts on node 97: 372582 
  Number of connections on node 101: 70726 
  Number of synaptic contacts on node 101: 373277 
  Number of connections on node 67: 70078 
  Number of synaptic contacts on node 67: 370065 
  Number of connections on node 99: 72316 
  Number of synaptic contacts on node 99: 378177 
  Number of connections on node 71: 70572 
  Number of synaptic contacts on node 71: 370873 
  Number of connections on node 75: 70281 
  Number of synaptic contacts on node 75: 368244 
  Number of connections on node 81: 71161 
  Number of synaptic contacts on node 81: 374392 
  Number of connections on node 87: 70533 
  Number of synaptic contacts on node 87: 369978 
  Number of connections on node 109: 69928 
  Number of synaptic contacts on node 109: 366743 
  Number of connections on node 63: 70128 
  Number of synaptic contacts on node 63: 364670 
  Number of connections on node 93: 72455 
  Number of synaptic contacts on node 93: 379213 
  Number of connections on node 125: 72801 
  Number of synaptic contacts on node 125: 381654 
  Number of connections on node 117: 69309 
  Number of synaptic contacts on node 117: 363146 
  Number of connections on node 121: 70967 
  Number of synaptic contacts on node 121: 372683 
  Number of connections on node 77: 69467 
  Number of synaptic contacts on node 77: 362467 
  Done; cell connection time = 11816.78 s.
Adding stims...
  Number of stims on node 6: 2603 
  Number of stims on node 42: 2583 
  Number of stims on node 26: 2583 
  Number of stims on node 10: 2603 
  Number of stims on node 22: 2583 
  Number of stims on node 44: 2583 
  Number of stims on node 19: 2603 
  Number of stims on node 0: 2603 
  Number of stims on node 4: 2603 
  Number of stims on node 1: 2603 
  Number of stims on node 11: 2603 
  Number of stims on node 51: 2583 
  Number of stims on node 20: 2583 
  Number of stims on node 18: 2603 
  Number of stims on node 115: 2593 
  Number of stims on node 12: 2603 
  Number of stims on node 52: 2583 
  Number of stims on node 60: 2583 
  Number of stims on node 91: 2582 
  Number of stims on node 38: 2583 
  Number of stims on node 74: 2582 
  Number of stims on node 58: 2583 
  Number of stims on node 109: 2603 
  Number of stims on node 28: 2583 
  Number of stims on node 123: 2593 
  Number of stims on node 15: 2603 
  Number of stims on node 108: 2603 
  Number of stims on node 39: 2583 
  Number of stims on node 125: 2593 
  Number of stims on node 47: 2583 
  Number of stims on node 116: 2593 
  Number of stims on node 34: 2583 
  Number of stims on node 84: 2582 
  Number of stims on node 111: 2603 
  Number of stims on node 114: 2593 
  Number of stims on node 106: 2603 
  Number of stims on node 67: 2583 
  Number of stims on node 107: 2603 
  Number of stims on node 100: 2603 
  Number of stims on node 36: 2583 
  Number of stims on node 23: 2583 
  Number of stims on node 105: 2603 
  Number of stims on node 122: 2593 
  Number of stims on node 71: 2583 
  Number of stims on node 103: 2603 
  Number of stims on node 76: 2582 
  Number of stims on node 119: 2593 
  Number of stims on node 124: 2593 
  Number of stims on node 8: 2603 
  Number of stims on node 3: 2603 
  Number of stims on node 83: 2582 
  Number of stims on node 95: 2603 
  Number of stims on node 94: 2603 
  Number of stims on node 89: 2582 
  Number of stims on node 101: 2603 
  Number of stims on node 110: 2603 
  Number of stims on node 27: 2583 
  Number of stims on node 30: 2583 
  Number of stims on node 127: 2593 
  Number of stims on node 118: 2593 
  Number of stims on node 24: 2583 
  Number of stims on node 16: 2603 
  Number of stims on node 75: 2582 
  Number of stims on node 5: 2603 
  Number of stims on node 92: 2582 
  Number of stims on node 25: 2583 
  Number of stims on node 82: 2582 
  Number of stims on node 86: 2582 
  Number of stims on node 104: 2603 
  Number of stims on node 102: 2603 
  Number of stims on node 68: 2583 
  Number of stims on node 113: 2603 
  Number of stims on node 93: 2582 
  Number of stims on node 69: 2583 
  Number of stims on node 21: 2583 
  Number of stims on node 98: 2603 
  Number of stims on node 57: 2583 
  Number of stims on node 53: 2583 
  Number of stims on node 50: 2583 
  Number of stims on node 56: 2583 
  Number of stims on node 65: 2583 
  Number of stims on node 96: 2603 
  Number of stims on node 117: 2593 
  Number of stims on node 85: 2582 
  Number of stims on node 79: 2582 
  Number of stims on node 2: 2603 
  Number of stims on node 48: 2583 
  Number of stims on node 35: 2583 
  Number of stims on node 66: 2583 
  Number of stims on node 7: 2603 
  Number of stims on node 99: 2603 
  Number of stims on node 54: 2583 
  Number of stims on node 97: 2603 
  Number of stims on node 61: 2583 
  Number of stims on node 14: 2603 
  Number of stims on node 126: 2593 
  Number of stims on node 40: 2583 
  Number of stims on node 9: 2603 
  Number of stims on node 72: 2583 
  Number of stims on node 120: 2593 
  Number of stims on node 87: 2582 
  Number of stims on node 81: 2582 
  Number of stims on node 90: 2582 
  Number of stims on node 17: 2603 
  Number of stims on node 112: 2603 
  Number of stims on node 55: 2583 
  Number of stims on node 73: 2583 
  Number of stims on node 121: 2593 
  Number of stims on node 80: 2582 
  Number of stims on node 62: 2583 
  Number of stims on node 59: 2583 
  Number of stims on node 31: 2583 
  Number of stims on node 37: 2583 
  Number of stims on node 43: 2583 
  Number of stims on node 88: 2582 
  Number of stims on node 70: 2583 
  Number of stims on node 46: 2583 
  Number of stims on node 32: 2583 
  Number of stims on node 63: 2583 
  Number of stims on node 33: 2583 
  Number of stims on node 13: 2603 
  Number of stims on node 49: 2583 
  Number of stims on node 78: 2582 
  Number of stims on node 64: 2583 
  Number of stims on node 29: 2583 
  Number of stims on node 77: 2582 
  Number of stims on node 41: 2583 
  Number of stims on node 45: 2583 
  Done; cell stims creation time = 8.41 s.
Recording 7 traces of 1 types on node 22
Recording 4 traces of 1 types on node 47
Recording 5 traces of 1 types on node 23
Recording 9 traces of 1 types on node 1
Recording 7 traces of 1 types on node 63
Recording 8 traces of 1 types on node 6
Recording 10 traces of 1 types on node 119
Recording 9 traces of 1 types on node 115
Recording 7 traces of 1 types on node 19
Recording 7 traces of 1 types on node 71
Recording 4 traces of 1 types on node 32
Recording 13 traces of 1 types on node 109
Recording 5 traces of 1 types on node 33
Recording 8 traces of 1 types on node 31
Recording 11 traces of 1 types on node 105
Recording 6 traces of 1 types on node 42
Recording 9 traces of 1 types on node 93
Recording 8 traces of 1 types on node 8
Recording 9 traces of 1 types on node 27
Recording 8 traces of 1 types on node 12
Recording 8 traces of 1 types on node 79
Recording 12 traces of 1 types on node 91
Recording 7 traces of 1 types on node 29
Recording 5 traces of 1 types on node 55
Recording 5 traces of 1 types on node 21
Recording 8 traces of 1 types on node 87
Recording 10 traces of 1 types on node 4
Recording 3 traces of 1 types on node 37
Recording 6 traces of 1 types on node 67
Recording 7 traces of 1 types on node 53
Recording 8 traces of 1 types on node 74
Recording 5 traces of 1 types on node 20
Recording 2 traces of 1 types on node 39
Recording 12 traces of 1 types on node 0
Recording 8 traces of 1 types on node 38
Recording 9 traces of 1 types on node 57
Recording 7 traces of 1 types on node 102
Recording 5 traces of 1 types on node 70
Recording 8 traces of 1 types on node 111
Recording 4 traces of 1 types on node 41
Recording 6 traces of 1 types on node 30
Recording 10 traces of 1 types on node 52
Recording 7 traces of 1 types on node 125
Recording 5 traces of 1 types on node 17
Recording 10 traces of 1 types on node 88
Recording 10 traces of 1 types on node 126
Recording 8 traces of 1 types on node 117
Recording 9 traces of 1 types on node 99
Recording 12 traces of 1 types on node 124
Recording 8 traces of 1 types on node 10
Recording 7 traces of 1 types on node 9
Recording 8 traces of 1 types on node 11
Recording 5 traces of 1 types on node 58
Recording 10 traces of 1 types on node 51
Recording 7 traces of 1 types on node 3
Recording 9 traces of 1 types on node 68
Recording 8 traces of 1 types on node 77
Recording 4 traces of 1 types on node 28
Recording 7 traces of 1 types on node 97
Recording 4 traces of 1 types on node 13
Recording 9 traces of 1 types on node 44
Recording 9 traces of 1 types on node 54
Recording 8 traces of 1 types on node 2
Recording 7 traces of 1 types on node 7
Recording 12 traces of 1 types on node 112
Recording 7 traces of 1 types on node 96
Recording 7 traces of 1 types on node 106
Recording 7 traces of 1 types on node 108
Recording 9 traces of 1 types on node 26
Recording 7 traces of 1 types on node 66
Recording 3 traces of 1 types on node 43
Recording 7 traces of 1 types on node 18
Recording 12 traces of 1 types on node 83
Recording 4 traces of 1 types on node 69
Recording 6 traces of 1 types on node 90
Recording 5 traces of 1 types on node 35
Recording 6 traces of 1 types on node 46
Recording 8 traces of 1 types on node 104
Recording 5 traces of 1 types on node 40
Recording 10 traces of 1 types on node 118
Recording 6 traces of 1 types on node 72
Recording 7 traces of 1 types on node 110
Recording 5 traces of 1 types on node 120
Recording 10 traces of 1 types on node 121
Recording 10 traces of 1 types on node 86
Recording 13 traces of 1 types on node 60
Recording 7 traces of 1 types on node 14
Recording 8 traces of 1 types on node 56
Recording 6 traces of 1 types on node 36
Recording 5 traces of 1 types on node 50
Recording 5 traces of 1 types on node 65
Recording 6 traces of 1 types on node 59
Recording 7 traces of 1 types on node 5
Recording 9 traces of 1 types on node 101
Recording 9 traces of 1 types on node 75
Recording 9 traces of 1 types on node 100
Recording 13 traces of 1 types on node 107
Recording 12 traces of 1 types on node 114
Recording 8 traces of 1 types on node 16
Recording 7 traces of 1 types on node 94
Recording 9 traces of 1 types on node 98
Recording 9 traces of 1 types on node 64
Recording 9 traces of 1 types on node 61
Recording 8 traces of 1 types on node 113
Recording 7 traces of 1 types on node 84
Recording 6 traces of 1 types on node 24
Recording 4 traces of 1 types on node 25
Recording 8 traces of 1 types on node 85
Recording 6 traces of 1 types on node 81
Recording 5 traces of 1 types on node 73
Recording 2 traces of 1 types on node 92
Recording 6 traces of 1 types on node 49
Recording 2 traces of 1 types on node 34
Recording 9 traces of 1 types on node 116
Recording 7 traces of 1 types on node 76
Recording 3 traces of 1 types on node 122
Recording 10 traces of 1 types on node 82
Recording 8 traces of 1 types on node 123
Recording 5 traces of 1 types on node 95
Recording 8 traces of 1 types on node 45
Recording 7 traces of 1 types on node 127
Recording 8 traces of 1 types on node 62
Recording 9 traces of 1 types on node 103
Recording 6 traces of 1 types on node 78
Recording 7 traces of 1 types on node 89
Recording 5 traces of 1 types on node 48
Recording 9 traces of 1 types on node 80
Recording 5 traces of 1 types on node 15
0.0s

Running simulation using NEURON for 12000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
  Done; run time = 82100.80 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 17.42 s.

Analyzing...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
There was an exception in prepareSpikeData()

Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
  Cells: 33738
  Connections: 0 (0.00 per cell)
  Spikes: 1039358 (2.57 Hz)
  Simulated time: 12.0 s; 128 workers
  Run time: 82100.80 s

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.000 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.010 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.000 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 1.194 Hz
   L23_BP_bIR : 1.021 Hz
   L23_BP_bNA : 2.774 Hz
   L23_BP_cAC : 2.071 Hz
   L23_BP_cNA : 5.042 Hz
   L23_BP_dST : 1.083 Hz
   L23_BTC_bAC : 0.033 Hz
   L23_BTC_bIR : 0.012 Hz
   L23_BTC_bNA : 0.043 Hz
   L23_BTC_cAC : 0.051 Hz
   L23_BTC_cNA : 0.051 Hz
   L23_ChC_cAC : 0.337 Hz
   L23_ChC_cNA : 0.174 Hz
   L23_ChC_dNA : 0.122 Hz
   L23_DBC_bAC : 0.451 Hz
   L23_DBC_bIR : 0.068 Hz
   L23_DBC_bNA : 0.260 Hz
   L23_DBC_cAC : 0.206 Hz
   L23_LBC_bAC : 0.031 Hz
   L23_LBC_bNA : 0.519 Hz
   L23_LBC_cAC : 0.060 Hz
   L23_LBC_cNA : 0.076 Hz
   L23_LBC_cST : 0.208 Hz
   L23_LBC_dNA : 0.426 Hz
   L23_MC_bAC : 0.008 Hz
   L23_MC_bNA : 0.025 Hz
   L23_MC_cAC : 0.022 Hz
   L23_MC_cNA : 0.025 Hz
   L23_MC_dNA : 0.008 Hz
   L23_NBC_bAC : 0.018 Hz
   L23_NBC_bNA : 0.222 Hz
   L23_NBC_cAC : 0.050 Hz
   L23_NBC_cIR : 0.028 Hz
   L23_NBC_cNA : 0.051 Hz
   L23_NBC_dNA : 0.132 Hz
   L23_NGC_bNA : 0.133 Hz
   L23_NGC_cAC : 0.100 Hz
   L23_NGC_cNA : 0.102 Hz
   L23_NGC_cST : 0.050 Hz
   L23_PC_cAD : 0.334 Hz
   L23_SBC_bNA : 0.486 Hz
   L23_SBC_cAC : 0.479 Hz
   L23_SBC_dNA : 0.183 Hz
   L4_BP_bAC : 8.417 Hz
   L4_BP_bIR : 5.917 Hz
   L4_BP_bNA : 4.542 Hz
   L4_BP_cAC : 5.375 Hz
   L4_BP_cNA : 12.750 Hz
   L4_BP_dST : 0.083 Hz
   L4_BTC_bAC : 3.833 Hz
   L4_BTC_bIR : 0.125 Hz
   L4_BTC_bST : 0.333 Hz
   L4_BTC_cAC : 0.435 Hz
   L4_BTC_cNA : 0.139 Hz
   L4_BTC_dNA : 0.167 Hz
   L4_ChC_cAC : 8.639 Hz
   L4_ChC_cNA : 3.833 Hz
   L4_ChC_dNA : 0.500 Hz
   L4_DBC_bAC : 2.146 Hz
   L4_DBC_bIR : 0.077 Hz
   L4_DBC_bNA : 0.188 Hz
   L4_DBC_bST : 0.062 Hz
   L4_DBC_cAC : 0.542 Hz
   L4_DBC_cIR : 0.071 Hz
   L4_DBC_cNA : 0.188 Hz
   L4_LBC_cAC : 2.458 Hz
   L4_LBC_cNA : 3.190 Hz
   L4_LBC_cST : 1.739 Hz
   L4_LBC_dNA : 4.333 Hz
   L4_LBC_dST : 1.231 Hz
   L4_MC_bAC : 0.023 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.046 Hz
   L4_MC_cNA : 0.042 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 3.725 Hz
   L4_NBC_cIR : 0.500 Hz
   L4_NBC_cNA : 2.702 Hz
   L4_NBC_dNA : 1.877 Hz
   L4_NGC_bNA : 0.417 Hz
   L4_NGC_cAC : 1.000 Hz
   L4_NGC_cNA : 0.639 Hz
   L4_NGC_cST : 0.083 Hz
   L4_PC_cAD : 1.488 Hz
   L4_SBC_bNA : 6.103 Hz
   L4_SBC_cAC : 5.424 Hz
   L4_SBC_dNA : 5.613 Hz
   L4_SP_cAD : 2.838 Hz
   L4_SS_cAD : 3.145 Hz
   L5_BP_bAC : 3.694 Hz
   L5_BP_bIR : 0.200 Hz
   L5_BP_bNA : 7.880 Hz
   L5_BP_cAC : 9.991 Hz
   L5_BP_cNA : 12.550 Hz
   L5_BP_dST : 0.194 Hz
   L5_BTC_bAC : 4.417 Hz
   L5_BTC_cAC : 1.578 Hz
   L5_BTC_cNA : 1.397 Hz
   L5_ChC_cAC : 15.964 Hz
   L5_ChC_cNA : 21.536 Hz
   L5_ChC_dNA : 7.067 Hz
   L5_DBC_bAC : 3.611 Hz
   L5_DBC_bIR : 0.083 Hz
   L5_DBC_bNA : 0.463 Hz
   L5_DBC_bST : 0.167 Hz
   L5_DBC_cAC : 0.880 Hz
   L5_DBC_cIR : 0.142 Hz
   L5_DBC_cNA : 1.250 Hz
   L5_LBC_bAC : 6.153 Hz
   L5_LBC_cAC : 10.470 Hz
   L5_LBC_cIR : 1.385 Hz
   L5_LBC_cNA : 18.514 Hz
   L5_LBC_cST : 11.937 Hz
   L5_LBC_dNA : 19.349 Hz
   L5_LBC_dST : 9.163 Hz
   L5_MC_bAC : 0.376 Hz
   L5_MC_bIR : 0.066 Hz
   L5_MC_bST : 0.068 Hz
   L5_MC_cAC : 0.787 Hz
   L5_MC_cNA : 0.234 Hz
   L5_MC_cST : 0.052 Hz
   L5_MC_dNA : 0.062 Hz
   L5_NBC_bAC : 4.113 Hz
   L5_NBC_bIR : 0.643 Hz
   L5_NBC_bST : 3.781 Hz
   L5_NBC_cAC : 13.094 Hz
   L5_NBC_cIR : 4.137 Hz
   L5_NBC_cNA : 19.222 Hz
   L5_NBC_cST : 7.175 Hz
   L5_NBC_dST : 8.468 Hz
   L5_NGC_bNA : 5.667 Hz
   L5_NGC_cAC : 9.083 Hz
   L5_NGC_cNA : 13.300 Hz
   L5_NGC_cST : 0.167 Hz
   L5_SBC_bNA : 6.093 Hz
   L5_SBC_cAC : 9.676 Hz
   L5_SBC_dNA : 14.202 Hz
   L5_STPC_cAD : 4.235 Hz
   L5_TTPC1_cAD : 3.420 Hz
   L5_TTPC2_cAD : 3.618 Hz
   L5_UTPC_cAD : 5.948 Hz
   L6_BPC_cAD : 1.950 Hz
   L6_BP_bAC : 3.444 Hz
   L6_BP_bIR : 0.125 Hz
   L6_BP_bNA : 6.140 Hz
   L6_BP_cAC : 7.250 Hz
   L6_BP_cNA : 6.833 Hz
   L6_BP_dST : 0.083 Hz
   L6_BTC_bAC : 3.783 Hz
   L6_BTC_cAC : 2.909 Hz
   L6_BTC_cNA : 2.392 Hz
   L6_ChC_cAC : 11.847 Hz
   L6_ChC_cNA : 28.542 Hz
   L6_ChC_dNA : 10.354 Hz
   L6_DBC_bAC : 5.889 Hz
   L6_DBC_bIR : 0.083 Hz
   L6_DBC_bNA : 0.139 Hz
   L6_DBC_bST : 0.056 Hz
   L6_DBC_cAC : 4.944 Hz
   L6_DBC_cIR : 0.194 Hz
   L6_DBC_cNA : 1.361 Hz
   L6_IPC_cAD : 2.647 Hz
   L6_LBC_bAC : 4.257 Hz
   L6_LBC_bIR : 1.057 Hz
   L6_LBC_bNA : 21.167 Hz
   L6_LBC_bST : 6.102 Hz
   L6_LBC_cNA : 25.210 Hz
   L6_LBC_cST : 5.690 Hz
   L6_MC_bAC : 0.039 Hz
   L6_MC_bIR : 0.009 Hz
   L6_MC_bNA : 0.054 Hz
   L6_MC_bST : 0.018 Hz
   L6_MC_cAC : 0.084 Hz
   L6_MC_cIR : 0.012 Hz
   L6_MC_cNA : 0.077 Hz
   L6_NBC_bAC : 4.274 Hz
   L6_NBC_bIR : 1.083 Hz
   L6_NBC_bST : 7.997 Hz
   L6_NBC_cAC : 8.355 Hz
   L6_NBC_cIR : 2.720 Hz
   L6_NBC_cNA : 19.088 Hz
   L6_NBC_cST : 10.032 Hz
   L6_NBC_dST : 11.994 Hz
   L6_NGC_bNA : 5.833 Hz
   L6_NGC_cAC : 7.333 Hz
   L6_NGC_cNA : 9.409 Hz
   L6_NGC_cST : 0.125 Hz
   L6_SBC_bNA : 12.569 Hz
   L6_SBC_cAC : 15.201 Hz
   L6_SBC_dNA : 8.829 Hz
   L6_TPC_L1_cAD : 2.422 Hz
   L6_TPC_L4_cAD : 3.200 Hz
   L6_UTPC_cAD : 3.415 Hz
   ss_RTN_m : 11.493 Hz
   VPM_sTC : 2.905 Hz
   VPM_TC : 2.746 Hz
Saving output as ../data/v8_batch8/v8_batch8_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 67.02 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 251.19 s

Total time = 94408.73 s
Preparing spike data...
Plotting spike frequency...
