numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]Loading simConfig...

Loading simConfig...
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch9/v8_batch9_0_0_cfg.json
Loading file ../data/v8_batch9/v8_batch9_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py
Importing netParams from ../data/v8_batch9/v8_batch9_netParams.py

Start time:  2025-08-06 06:58:31.390009

Creating network of 210 cell populations on 128 hosts...
  Number of cells on node 119: 263 
  Number of cells on node 75: 263 
  Number of cells on node 60: 264 
  Number of cells on node 78: 263 
  Number of cells on node 86: 263 
  Number of cells on node 36: 264 
  Number of cells on node 40: 264 
  Number of cells on node 53: 264 
  Number of cells on node 80: 263 
  Number of cells on node 38: 264 
  Number of cells on node 49: 264 
  Number of cells on node 30: 264 
  Number of cells on node 110: 263 
  Number of cells on node 52: 264 
  Number of cells on node 98: 263 
  Number of cells on node 93: 263 
  Number of cells on node 94: 263 
  Number of cells on node 22: 264 
  Number of cells on node 59: 264 
  Number of cells on node 120: 263 
  Number of cells on node 44: 264 
  Number of cells on node 79: 263 
  Number of cells on node 112: 263 
  Number of cells on node 99: 263 
  Number of cells on node 122: 263 
  Number of cells on node 72: 264 
  Number of cells on node 106: 263 
  Number of cells on node 70: 264 
  Number of cells on node 43: 264 
  Number of cells on node 63: 264 
  Number of cells on node 84: 263 
  Number of cells on node 34: 264 
  Number of cells on node 29: 264 
  Number of cells on node 56: 264 
  Number of cells on node 46: 264 
  Number of cells on node 51: 264 
  Number of cells on node 74: 263 
  Number of cells on node 111: 263 
  Number of cells on node 85: 263 
  Number of cells on node 88: 263 
  Number of cells on node 55: 264 
  Number of cells on node 117: 263 
  Number of cells on node 83: 263 
  Number of cells on node 116: 263 
  Number of cells on node 64: 264 
  Number of cells on node 118: 263 
  Number of cells on node 124: 263 
  Number of cells on node 101: 263 
  Number of cells on node 109: 263 
  Number of cells on node 125: 263 
  Number of cells on node 105: 263 
  Number of cells on node 0: 264 
  Number of cells on node 13: 264 
  Number of cells on node 21: 264 
  Number of cells on node 23: 264 
  Number of cells on node 3: 264 
  Number of cells on node 4: 264 
  Number of cells on node 16: 264 
  Number of cells on node 5: 264 
  Number of cells on node 6: 264 
  Number of cells on node 123: 263 
  Number of cells on node 9: 264 
  Number of cells on node 7: 264 
  Number of cells on node 107: 263 
  Number of cells on node 11: 264 
  Number of cells on node 68: 264 
  Number of cells on node 17: 264 
  Number of cells on node 31: 264 
  Number of cells on node 65: 264 
  Number of cells on node 71: 264 
  Number of cells on node 15: 264 
  Number of cells on node 35: 264 
  Number of cells on node 12: 264 
  Number of cells on node 97: 263 
  Number of cells on node 100: 263 
  Number of cells on node 54: 264 
  Number of cells on node 33: 264 
  Number of cells on node 50: 264 
  Number of cells on node 91: 263 
  Number of cells on node 82: 263 
  Number of cells on node 27: 264 
  Number of cells on node 41: 264 
  Number of cells on node 66: 264 
  Number of cells on node 39: 264 
  Number of cells on node 18: 264 
  Number of cells on node 25: 264 
  Number of cells on node 92: 263 
  Number of cells on node 103: 263 
  Number of cells on node 67: 264 
  Number of cells on node 69: 264 
  Number of cells on node 32: 264 
  Number of cells on node 45: 264 
  Number of cells on node 90: 263 
  Number of cells on node 48: 264 
  Number of cells on node 42: 264 
  Number of cells on node 114: 263 
  Number of cells on node 95: 263 
  Number of cells on node 104: 263 
  Number of cells on node 58: 264 
  Number of cells on node 26: 264 
  Number of cells on node 28: 264 
  Number of cells on node 87: 263 
  Number of cells on node 113: 263 
  Number of cells on node 24: 264 
  Number of cells on node 73: 264 
  Number of cells on node 96: 263 
  Number of cells on node 57: 264 
  Number of cells on node 127: 263 
  Number of cells on node 108: 263 
  Number of cells on node 102: 263 
  Number of cells on node 19: 264 
  Number of cells on node 77: 263 
  Number of cells on node 37: 264 
  Number of cells on node 89: 263 
  Number of cells on node 61: 264 
  Number of cells on node 14: 264 
  Number of cells on node 81: 263 
  Number of cells on node 115: 263 
  Number of cells on node 121: 263 
  Number of cells on node 47: 264 
  Number of cells on node 8: 264 
  Number of cells on node 76: 263 
  Number of cells on node 10: 264 
  Number of cells on node 1: 264 
  Number of cells on node 2: 264 
  Number of cells on node 126: 263 
  Number of cells on node 62: 264 
  Number of cells on node 20: 264 
  Done; cell creation time = 17.77 s.
Making connections...
  Number of connections on node 23: 70749 
  Number of synaptic contacts on node 23: 375166 
  Number of connections on node 45: 70758 
  Number of synaptic contacts on node 45: 369425 
  Number of connections on node 39: 69529 
  Number of synaptic contacts on node 39: 363815 
  Number of connections on node 47: 70496 
  Number of synaptic contacts on node 47: 367929 
  Number of connections on node 21: 70276 
  Number of synaptic contacts on node 21: 368959 
  Number of connections on node 61: 68821 
  Number of synaptic contacts on node 61: 362736 
  Number of connections on node 37: 71043 
  Number of synaptic contacts on node 37: 370125 
  Number of connections on node 13: 69073 
  Number of synaptic contacts on node 13: 363554 
  Number of connections on node 29: 72234 
  Number of synaptic contacts on node 29: 375575 
  Number of connections on node 5: 68819 
  Number of synaptic contacts on node 5: 360640 
  Number of connections on node 7: 69067 
  Number of synaptic contacts on node 7: 361426 
  Number of connections on node 55: 69539 
  Number of synaptic contacts on node 55: 363932 
  Number of connections on node 15: 71703 
  Number of synaptic contacts on node 15: 380121 
  Number of connections on node 31: 70346 
  Number of synaptic contacts on node 31: 371104 
  Number of connections on node 33: 70561 
  Number of synaptic contacts on node 33: 369197 
  Number of connections on node 19: 69805 
  Number of synaptic contacts on node 19: 367907 
  Number of connections on node 11: 70587 
  Number of synaptic contacts on node 11: 370320 
  Number of connections on node 27: 71476 
  Number of synaptic contacts on node 27: 372880 
  Number of connections on node 35: 69898 
  Number of synaptic contacts on node 35: 364672 
  Number of connections on node 1: 68002 
  Number of synaptic contacts on node 1: 357866 
  Number of connections on node 51: 71362 
  Number of synaptic contacts on node 51: 371751 
  Number of connections on node 41: 71027 
  Number of synaptic contacts on node 41: 371291 
  Number of connections on node 59: 70375 
  Number of synaptic contacts on node 59: 368782 
  Number of connections on node 17: 71479 
  Number of synaptic contacts on node 17: 377006 
  Number of connections on node 43: 70286 
  Number of synaptic contacts on node 43: 367083 
  Number of connections on node 49: 69489 
  Number of synaptic contacts on node 49: 363397 
  Number of connections on node 25: 70633 
  Number of synaptic contacts on node 25: 370613 
  Number of connections on node 3: 68273 
  Number of synaptic contacts on node 3: 357315 
  Number of connections on node 9: 70681 
  Number of synaptic contacts on node 9: 372583 
  Number of connections on node 70: 68937 
  Number of synaptic contacts on node 70: 360562 
  Number of connections on node 111: 70839 
  Number of synaptic contacts on node 111: 371921 
  Number of connections on node 57: 71121 
  Number of synaptic contacts on node 57: 371743 
  Number of connections on node 84: 68546 
  Number of synaptic contacts on node 84: 362005 
  Number of connections on node 103: 70570 
  Number of synaptic contacts on node 103: 368792 
  Number of connections on node 76: 71169 
  Number of synaptic contacts on node 76: 373125 
  Number of connections on node 102: 69653 
  Number of synaptic contacts on node 102: 365324 
  Number of connections on node 78: 71761 
  Number of synaptic contacts on node 78: 377744 
  Number of connections on node 53: 71729 
  Number of synaptic contacts on node 53: 375624 
  Number of connections on node 118: 69592 
  Number of synaptic contacts on node 118: 365950 
  Number of connections on node 85: 68700 
  Number of synaptic contacts on node 85: 360849 
  Number of connections on node 92: 69887 
  Number of synaptic contacts on node 92: 365867 
  Number of connections on node 94: 69100 
  Number of synaptic contacts on node 94: 359181 
  Number of connections on node 110: 69420 
  Number of synaptic contacts on node 110: 363978 
  Number of connections on node 124: 71897 
  Number of synaptic contacts on node 124: 377069 
  Number of connections on node 95: 69585 
  Number of synaptic contacts on node 95: 362879 
  Number of connections on node 69: 72236 
  Number of synaptic contacts on node 69: 380447 
  Number of connections on node 117: 69626 
  Number of synaptic contacts on node 117: 364613 
  Number of connections on node 68: 70239 
  Number of synaptic contacts on node 68: 363907 
  Number of connections on node 71: 70633 
  Number of synaptic contacts on node 71: 370778 
  Number of connections on node 126: 70723 
  Number of synaptic contacts on node 126: 373620 
  Number of connections on node 116: 70660 
  Number of synaptic contacts on node 116: 369391 
  Number of connections on node 86: 67972 
  Number of synaptic contacts on node 86: 357017 
  Number of connections on node 125: 72963 
  Number of synaptic contacts on node 125: 382185 
  Number of connections on node 119: 69000 
  Number of synaptic contacts on node 119: 360327 
  Number of connections on node 108: 70371 
  Number of synaptic contacts on node 108: 368078 
  Number of connections on node 44: 71210 
  Number of synaptic contacts on node 44: 371230 
  Number of connections on node 127: 71215 
  Number of synaptic contacts on node 127: 370988 
  Number of connections on node 60: 69978 
  Number of synaptic contacts on node 60: 365474 
  Number of connections on node 90: 70622 
  Number of synaptic contacts on node 90: 369680 
  Number of connections on node 109: 69753 
  Number of synaptic contacts on node 109: 367137 
  Number of connections on node 79: 70054 
  Number of synaptic contacts on node 79: 365524 
  Number of connections on node 112: 70013 
  Number of synaptic contacts on node 112: 366510 
  Number of connections on node 77: 70250 
  Number of synaptic contacts on node 77: 367769 
  Number of connections on node 98: 70676 
  Number of synaptic contacts on node 98: 371217 
  Number of connections on node 87: 71053 
  Number of synaptic contacts on node 87: 373846 
  Number of connections on node 38: 70372 
  Number of synaptic contacts on node 38: 368526 
  Number of connections on node 93: 72525 
  Number of synaptic contacts on node 93: 378273 
  Number of connections on node 28: 71959 
  Number of synaptic contacts on node 28: 376883 
  Number of connections on node 20: 72600 
  Number of synaptic contacts on node 20: 380887 
  Number of connections on node 100: 71147 
  Number of synaptic contacts on node 100: 373113 
  Number of connections on node 46: 70259 
  Number of synaptic contacts on node 46: 368953 
  Number of connections on node 114: 69083 
  Number of synaptic contacts on node 114: 359750 
  Number of connections on node 107: 69690 
  Number of synaptic contacts on node 107: 363763 
  Number of connections on node 36: 71348 
  Number of synaptic contacts on node 36: 372754 
  Number of connections on node 106: 68852 
  Number of synaptic contacts on node 106: 358380 
  Number of connections on node 52: 71648 
  Number of synaptic contacts on node 52: 375735 
  Number of connections on node 74: 69960 
  Number of synaptic contacts on node 74: 368350 
  Number of connections on node 88: 69600 
  Number of synaptic contacts on node 88: 366258 
  Number of connections on node 80: 69925 
  Number of synaptic contacts on node 80: 366564 
  Number of connections on node 75: 70453 
  Number of synaptic contacts on node 75: 368314 
  Number of connections on node 66: 70690 
  Number of synaptic contacts on node 66: 369574 
  Number of connections on node 30: 67240 
  Number of synaptic contacts on node 30: 352028 
  Number of connections on node 89: 70041 
  Number of synaptic contacts on node 89: 367581 
  Number of connections on node 82: 70123 
  Number of synaptic contacts on node 82: 365804 
  Number of connections on node 120: 70694 
  Number of synaptic contacts on node 120: 370893 
  Number of connections on node 4: 69053 
  Number of synaptic contacts on node 4: 362431 
  Number of connections on node 97: 71729 
  Number of synaptic contacts on node 97: 373341 
  Number of connections on node 64: 69673 
  Number of synaptic contacts on node 64: 365265 
  Number of connections on node 96: 70634 
  Number of synaptic contacts on node 96: 369154 
  Number of connections on node 14: 69873 
  Number of synaptic contacts on node 14: 367077 
  Number of connections on node 63: 69695 
  Number of synaptic contacts on node 63: 363263 
  Number of connections on node 72: 71593 
  Number of synaptic contacts on node 72: 373567 
  Number of connections on node 6: 70456 
  Number of synaptic contacts on node 6: 368220 
  Number of connections on node 101: 71048 
  Number of synaptic contacts on node 101: 374626 
  Number of connections on node 22: 71631 
  Number of synaptic contacts on node 22: 377809 
  Number of connections on node 123: 70188 
  Number of synaptic contacts on node 123: 369071 
  Number of connections on node 73: 71253 
  Number of synaptic contacts on node 73: 374595 
  Number of connections on node 67: 70061 
  Number of synaptic contacts on node 67: 367175 
  Number of connections on node 54: 70444 
  Number of synaptic contacts on node 54: 367885 
  Number of connections on node 121: 70841 
  Number of synaptic contacts on node 121: 371853 
  Number of connections on node 83: 69763 
  Number of synaptic contacts on node 83: 364368 
  Number of connections on node 105: 70438 
  Number of synaptic contacts on node 105: 370396 
  Number of connections on node 8: 70897 
  Number of synaptic contacts on node 8: 373522 
  Number of connections on node 113: 70081 
  Number of synaptic contacts on node 113: 366776 
  Number of connections on node 12: 69935 
  Number of synaptic contacts on node 12: 367899 
  Number of connections on node 62: 70045 
  Number of synaptic contacts on node 62: 365043 
  Number of connections on node 115: 69538 
  Number of synaptic contacts on node 115: 361280 
  Number of connections on node 24: 72217 
  Number of synaptic contacts on node 24: 378661 
  Number of connections on node 122: 69316 
  Number of synaptic contacts on node 122: 363446 
  Number of connections on node 91: 72160 
  Number of synaptic contacts on node 91: 377533 
  Number of connections on node 56: 69274 
  Number of synaptic contacts on node 56: 360917 
  Number of connections on node 99: 72289 
  Number of synaptic contacts on node 99: 378346 
  Number of connections on node 65: 69475 
  Number of synaptic contacts on node 65: 365074 
  Number of connections on node 104: 71027 
  Number of synaptic contacts on node 104: 371396 
  Number of connections on node 32: 69162 
  Number of synaptic contacts on node 32: 363122 
  Number of connections on node 2: 70030 
  Number of synaptic contacts on node 2: 366586 
  Number of connections on node 18: 68760 
  Number of synaptic contacts on node 18: 359049 
  Number of connections on node 81: 70914 
  Number of synaptic contacts on node 81: 373827 
  Number of connections on node 50: 70131 
  Number of synaptic contacts on node 50: 366655 
  Number of connections on node 34: 68834 
  Number of synaptic contacts on node 34: 359416 
  Number of connections on node 40: 70103 
  Number of synaptic contacts on node 40: 366476 
  Number of connections on node 48: 70665 
  Number of synaptic contacts on node 48: 369273 
  Number of connections on node 58: 70825 
  Number of synaptic contacts on node 58: 370321 
  Number of connections on node 10: 71820 
  Number of synaptic contacts on node 10: 375722 
  Number of connections on node 0: 69362 
  Number of synaptic contacts on node 0: 362684 
  Number of connections on node 42: 71515 
  Number of synaptic contacts on node 42: 373556 
  Number of connections on node 16: 70825 
  Number of synaptic contacts on node 16: 372298 
  Number of connections on node 26: 70718 
  Number of synaptic contacts on node 26: 371658 
  Done; cell connection time = 11589.92 s.
Adding stims...
  Number of stims on node 39: 2583 
  Number of stims on node 16: 2603 
  Number of stims on node 7: 2603 
  Number of stims on node 19: 2603 
  Number of stims on node 36: 2583 
  Number of stims on node 2: 2603 
  Number of stims on node 44: 2583 
  Number of stims on node 8: 2603 
  Number of stims on node 20: 2583 
  Number of stims on node 6: 2603 
  Number of stims on node 68: 2583 
  Number of stims on node 28: 2583 
  Number of stims on node 32: 2583 
  Number of stims on node 15: 2603 
  Number of stims on node 23: 2583 
  Number of stims on node 24: 2583 
  Number of stims on node 103: 2603 
  Number of stims on node 91: 2582 
  Number of stims on node 48: 2583 
  Number of stims on node 31: 2583 
  Number of stims on node 111: 2603 
  Number of stims on node 71: 2583 
  Number of stims on node 79: 2582 
  Number of stims on node 11: 2603 
  Number of stims on node 60: 2583 
  Number of stims on node 127: 2593 
  Number of stims on node 93: 2582 
  Number of stims on node 21: 2583 
  Number of stims on node 101: 2603 
  Number of stims on node 76: 2582 
  Number of stims on node 95: 2603 
  Number of stims on node 4: 2603 
  Number of stims on node 35: 2583 
  Number of stims on node 109: 2603 
  Number of stims on node 124: 2593 
  Number of stims on node 100: 2603 
  Number of stims on node 45: 2583 
  Number of stims on node 40: 2583 
  Number of stims on node 115: 2593 
  Number of stims on node 52: 2583 
  Number of stims on node 97: 2603 
  Number of stims on node 112: 2603 
  Number of stims on node 27: 2583 
  Number of stims on node 47: 2583 
  Number of stims on node 104: 2603 
  Number of stims on node 120: 2593 
  Number of stims on node 77: 2582 
  Number of stims on node 0: 2603 
  Number of stims on node 29: 2583 
  Number of stims on node 87: 2582 
  Number of stims on node 69: 2583 
  Number of stims on node 61: 2583 
  Number of stims on node 37: 2583 
  Number of stims on node 62: 2583 
  Number of stims on node 67: 2583 
  Number of stims on node 119: 2593 
  Number of stims on node 1: 2603 
  Number of stims on node 117: 2593 
  Number of stims on node 83: 2582 
  Number of stims on node 55: 2583 
  Number of stims on node 78: 2582 
  Number of stims on node 51: 2583 
  Number of stims on node 125: 2593 
  Number of stims on node 42: 2583 
  Number of stims on node 99: 2603 
  Number of stims on node 82: 2582 
  Number of stims on node 59: 2583 
  Number of stims on node 56: 2583 
  Number of stims on node 105: 2603 
  Number of stims on node 123: 2593 
  Number of stims on node 116: 2593 
  Number of stims on node 5: 2603 
  Number of stims on node 66: 2583 
  Number of stims on node 107: 2603 
  Number of stims on node 108: 2603 
  Number of stims on node 106: 2603 
  Number of stims on node 88: 2582 
  Number of stims on node 64: 2583 
  Number of stims on node 63: 2583 
  Number of stims on node 75: 2582 
  Number of stims on node 90: 2582 
  Number of stims on node 53: 2583 
  Number of stims on node 84: 2582 
  Number of stims on node 114: 2593 
  Number of stims on node 85: 2582 
  Number of stims on node 3: 2603 
  Number of stims on node 92: 2582 
  Number of stims on node 49: 2583 
  Number of stims on node 57: 2583 
  Number of stims on node 58: 2583 
  Number of stims on node 80: 2582 
  Number of stims on node 13: 2603 
  Number of stims on node 38: 2583 
  Number of stims on node 25: 2583 
  Number of stims on node 43: 2583 
  Number of stims on node 18: 2603 
  Number of stims on node 65: 2583 
  Number of stims on node 9: 2603 
  Number of stims on node 17: 2603 
  Number of stims on node 81: 2582 
  Number of stims on node 121: 2593 
  Number of stims on node 110: 2603 
  Number of stims on node 86: 2582 
  Number of stims on node 50: 2583 
  Number of stims on node 74: 2582 
  Number of stims on node 34: 2583 
  Number of stims on node 72: 2583 
  Number of stims on node 96: 2603 
  Number of stims on node 73: 2583 
  Number of stims on node 122: 2593 
  Number of stims on node 70: 2583 
  Number of stims on node 102: 2603 
  Number of stims on node 41: 2583 
  Number of stims on node 89: 2582 
  Number of stims on node 10: 2603 
  Number of stims on node 113: 2603 
  Number of stims on node 98: 2603 
  Number of stims on node 94: 2603 
  Number of stims on node 46: 2583 
  Number of stims on node 33: 2583 
  Number of stims on node 26: 2583 
  Number of stims on node 54: 2583 
  Number of stims on node 118: 2593 
  Number of stims on node 30: 2583 
  Number of stims on node 12: 2603 
  Number of stims on node 14: 2603 
  Number of stims on node 126: 2593 
  Number of stims on node 22: 2583 
  Done; cell stims creation time = 8.44 s.
Recording 2 traces of 1 types on node 39
Recording 8 traces of 1 types on node 8
Recording 9 traces of 1 types on node 115
Recording 7 traces of 1 types on node 19
Recording 7 traces of 1 types on node 18
Recording 8 traces of 1 types on node 104
Recording 6 traces of 1 types on node 24
Recording 9 traces of 1 types on node 44
Recording 5 traces of 1 types on node 23
Recording 5 traces of 1 types on node 35
Recording 9 traces of 1 types on node 57
Recording 3 traces of 1 types on node 43
Recording 5 traces of 1 types on node 58
Recording 8 traces of 1 types on node 56
Recording 7 traces of 1 types on node 84
Recording 5 traces of 1 types on node 55
Recording 7 traces of 1 types on node 5
Recording 6 traces of 1 types on node 36
Recording 7 traces of 1 types on node 97
Recording 12 traces of 1 types on node 0
Recording 5 traces of 1 types on node 95
Recording 5 traces of 1 types on node 33
Recording 2 traces of 1 types on node 34
Recording 7 traces of 1 types on node 66
Recording 10 traces of 1 types on node 4
Recording 9 traces of 1 types on node 93
Recording 7 traces of 1 types on node 3
Recording 12 traces of 1 types on node 83
Recording 4 traces of 1 types on node 32
Recording 7 traces of 1 types on node 63
Recording 12 traces of 1 types on node 91
Recording 7 traces of 1 types on node 53
Recording 5 traces of 1 types on node 48
Recording 9 traces of 1 types on node 27
Recording 6 traces of 1 types on node 81
Recording 7 traces of 1 types on node 94
Recording 9 traces of 1 types on node 100
Recording 8 traces of 1 types on node 11
Recording 13 traces of 1 types on node 60
Recording 9 traces of 1 types on node 99
Recording 7 traces of 1 types on node 7
Recording 9 traces of 1 types on node 68
Recording 4 traces of 1 types on node 69
Recording 7 traces of 1 types on node 29
Recording 8 traces of 1 types on node 77
Recording 5 traces of 1 types on node 17
Recording 4 traces of 1 types on node 28
Recording 7 traces of 1 types on node 110
Recording 9 traces of 1 types on node 98
Recording 8 traces of 1 types on node 12
Recording 4 traces of 1 types on node 47
Recording 11 traces of 1 types on node 105
Recording 5 traces of 1 types on node 120
Recording 8 traces of 1 types on node 117
Recording 6 traces of 1 types on node 67
Recording 5 traces of 1 types on node 40
Recording 5 traces of 1 types on node 50
Recording 9 traces of 1 types on node 75
Recording 7 traces of 1 types on node 125
Recording 9 traces of 1 types on node 101
Recording 12 traces of 1 types on node 112
Recording 10 traces of 1 types on node 88
Recording 5 traces of 1 types on node 15
Recording 8 traces of 1 types on node 87
Recording 10 traces of 1 types on node 118
Recording 10 traces of 1 types on node 82
Recording 2 traces of 1 types on node 92
Recording 7 traces of 1 types on node 22
Recording 9 traces of 1 types on node 54
Recording 9 traces of 1 types on node 64
Recording 7 traces of 1 types on node 71
Recording 8 traces of 1 types on node 74
Recording 10 traces of 1 types on node 52
Recording 9 traces of 1 types on node 61
Recording 6 traces of 1 types on node 78
Recording 6 traces of 1 types on node 42
Recording 6 traces of 1 types on node 46
Recording 7 traces of 1 types on node 76
Recording 5 traces of 1 types on node 21
Recording 7 traces of 1 types on node 106
Recording 8 traces of 1 types on node 111
Recording 10 traces of 1 types on node 86
Recording 10 traces of 1 types on node 119
Recording 9 traces of 1 types on node 103
Recording 9 traces of 1 types on node 1
Recording 7 traces of 1 types on node 9
Recording 9 traces of 1 types on node 80
Recording 3 traces of 1 types on node 122
Recording 8 traces of 1 types on node 85
Recording 7 traces of 1 types on node 14
Recording 8 traces of 1 types on node 38
Recording 8 traces of 1 types on node 6
Recording 6 traces of 1 types on node 49
Recording 5 traces of 1 types on node 73
Recording 6 traces of 1 types on node 30
Recording 5 traces of 1 types on node 65
Recording 8 traces of 1 types on node 10
Recording 7 traces of 1 types on node 89
Recording 6 traces of 1 types on node 90
Recording 12 traces of 1 types on node 114
Recording 3 traces of 1 types on node 37
Recording 8 traces of 1 types on node 113
Recording 4 traces of 1 types on node 13
Recording 4 traces of 1 types on node 41
Recording 5 traces of 1 types on node 70
Recording 7 traces of 1 types on node 102
Recording 10 traces of 1 types on node 121
Recording 10 traces of 1 types on node 126
Recording 4 traces of 1 types on node 25
Recording 13 traces of 1 types on node 107
Recording 6 traces of 1 types on node 59
Recording 7 traces of 1 types on node 108
Recording 8 traces of 1 types on node 2
Recording 8 traces of 1 types on node 16
Recording 10 traces of 1 types on node 51
Recording 8 traces of 1 types on node 31
Recording 13 traces of 1 types on node 109
Recording 8 traces of 1 types on node 123
Recording 9 traces of 1 types on node 116
Recording 12 traces of 1 types on node 124
Recording 8 traces of 1 types on node 45
Recording 8 traces of 1 types on node 79
Recording 8 traces of 1 types on node 62
Recording 5 traces of 1 types on node 20
Recording 9 traces of 1 types on node 26
Recording 7 traces of 1 types on node 127
Recording 7 traces of 1 types on node 96
Recording 6 traces of 1 types on node 72
0.0s

Running simulation using NEURON for 12000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
  Done; run time = 80604.31 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 16.74 s.

Analyzing...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()Plotting spike frequency...

There was an exception in plotSpikeFreq()


There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
  Cells: 33738
  Connections: 0 (0.00 per cell)
  Spikes: 1042602 (2.58 Hz)
  Simulated time: 12.0 s; 128 workers
  Run time: 80604.31 s
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.002 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.000 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.004 Hz
   L23_BP_bAC : 0.972 Hz
   L23_BP_bIR : 0.750 Hz
   L23_BP_bNA : 2.821 Hz
   L23_BP_cAC : 2.464 Hz
   L23_BP_cNA : 4.458 Hz
   L23_BP_dST : 0.222 Hz
   L23_BTC_bAC : 0.039 Hz
   L23_BTC_bIR : 0.036 Hz
   L23_BTC_bNA : 0.087 Hz
   L23_BTC_cAC : 0.039 Hz
   L23_BTC_cNA : 0.069 Hz
   L23_ChC_cAC : 0.286 Hz
   L23_ChC_cNA : 0.207 Hz
   L23_ChC_dNA : 0.111 Hz
   L23_DBC_bAC : 0.424 Hz
   L23_DBC_bIR : 0.062 Hz
   L23_DBC_bNA : 0.240 Hz
   L23_DBC_cAC : 0.257 Hz
   L23_LBC_bAC : 0.024 Hz
   L23_LBC_bNA : 0.580 Hz
   L23_LBC_cAC : 0.062 Hz
   L23_LBC_cNA : 0.088 Hz
   L23_LBC_cST : 0.216 Hz
   L23_LBC_dNA : 0.402 Hz
   L23_MC_bAC : 0.008 Hz
   L23_MC_bNA : 0.017 Hz
   L23_MC_cAC : 0.021 Hz
   L23_MC_cNA : 0.028 Hz
   L23_MC_dNA : 0.008 Hz
   L23_NBC_bAC : 0.030 Hz
   L23_NBC_bNA : 0.278 Hz
   L23_NBC_cAC : 0.058 Hz
   L23_NBC_cIR : 0.014 Hz
   L23_NBC_cNA : 0.058 Hz
   L23_NBC_dNA : 0.131 Hz
   L23_NGC_bNA : 0.100 Hz
   L23_NGC_cAC : 0.067 Hz
   L23_NGC_cNA : 0.102 Hz
   L23_NGC_cST : 0.067 Hz
   L23_PC_cAD : 0.335 Hz
   L23_SBC_bNA : 0.390 Hz
   L23_SBC_cAC : 0.553 Hz
   L23_SBC_dNA : 0.178 Hz
   L4_BP_bAC : 8.333 Hz
   L4_BP_bIR : 5.833 Hz
   L4_BP_bNA : 5.708 Hz
   L4_BP_cAC : 5.042 Hz
   L4_BP_cNA : 11.667 Hz
   L4_BP_dST : 0.083 Hz
   L4_BTC_bAC : 2.125 Hz
   L4_BTC_bIR : 0.083 Hz
   L4_BTC_bST : 0.167 Hz
   L4_BTC_cAC : 0.861 Hz
   L4_BTC_cNA : 0.111 Hz
   L4_BTC_dNA : 0.125 Hz
   L4_ChC_cAC : 8.361 Hz
   L4_ChC_cNA : 3.500 Hz
   L4_ChC_dNA : 0.292 Hz
   L4_DBC_bAC : 4.375 Hz
   L4_DBC_bIR : 0.071 Hz
   L4_DBC_bNA : 0.188 Hz
   L4_DBC_bST : 0.083 Hz
   L4_DBC_cAC : 0.208 Hz
   L4_DBC_cIR : 0.083 Hz
   L4_DBC_cNA : 0.146 Hz
   L4_LBC_cAC : 2.269 Hz
   L4_LBC_cNA : 3.071 Hz
   L4_LBC_cST : 1.747 Hz
   L4_LBC_dNA : 5.107 Hz
   L4_LBC_dST : 1.157 Hz
   L4_MC_bAC : 0.008 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.040 Hz
   L4_MC_cNA : 0.051 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 3.225 Hz
   L4_NBC_cIR : 0.700 Hz
   L4_NBC_cNA : 2.602 Hz
   L4_NBC_dNA : 2.139 Hz
   L4_NGC_bNA : 0.417 Hz
   L4_NGC_cAC : 0.333 Hz
   L4_NGC_cNA : 0.361 Hz
   L4_NGC_cST : 0.083 Hz
   L4_PC_cAD : 1.491 Hz
   L4_SBC_bNA : 5.786 Hz
   L4_SBC_cAC : 5.852 Hz
   L4_SBC_dNA : 5.103 Hz
   L4_SP_cAD : 2.847 Hz
   L4_SS_cAD : 3.162 Hz
   L5_BP_bAC : 4.056 Hz
   L5_BP_bIR : 0.233 Hz
   L5_BP_bNA : 8.769 Hz
   L5_BP_cAC : 9.426 Hz
   L5_BP_cNA : 14.317 Hz
   L5_BP_dST : 0.167 Hz
   L5_BTC_bAC : 4.776 Hz
   L5_BTC_cAC : 1.497 Hz
   L5_BTC_cNA : 1.872 Hz
   L5_ChC_cAC : 16.012 Hz
   L5_ChC_cNA : 21.369 Hz
   L5_ChC_dNA : 6.550 Hz
   L5_DBC_bAC : 3.231 Hz
   L5_DBC_bIR : 0.083 Hz
   L5_DBC_bNA : 0.648 Hz
   L5_DBC_bST : 0.139 Hz
   L5_DBC_cAC : 1.269 Hz
   L5_DBC_cIR : 0.137 Hz
   L5_DBC_cNA : 1.083 Hz
   L5_LBC_bAC : 5.993 Hz
   L5_LBC_cAC : 10.150 Hz
   L5_LBC_cIR : 1.436 Hz
   L5_LBC_cNA : 18.718 Hz
   L5_LBC_cST : 12.261 Hz
   L5_LBC_dNA : 19.189 Hz
   L5_LBC_dST : 8.837 Hz
   L5_MC_bAC : 0.346 Hz
   L5_MC_bIR : 0.061 Hz
   L5_MC_bST : 0.068 Hz
   L5_MC_cAC : 0.843 Hz
   L5_MC_cNA : 0.240 Hz
   L5_MC_cST : 0.057 Hz
   L5_MC_dNA : 0.078 Hz
   L5_NBC_bAC : 4.065 Hz
   L5_NBC_bIR : 0.655 Hz
   L5_NBC_bST : 4.037 Hz
   L5_NBC_cAC : 13.415 Hz
   L5_NBC_cIR : 4.369 Hz
   L5_NBC_cNA : 19.600 Hz
   L5_NBC_cST : 6.921 Hz
   L5_NBC_dST : 7.269 Hz
   L5_NGC_bNA : 7.000 Hz
   L5_NGC_cAC : 9.083 Hz
   L5_NGC_cNA : 13.400 Hz
   L5_NGC_cST : 0.250 Hz
   L5_SBC_bNA : 5.472 Hz
   L5_SBC_cAC : 10.130 Hz
   L5_SBC_dNA : 14.869 Hz
   L5_STPC_cAD : 4.241 Hz
   L5_TTPC1_cAD : 3.411 Hz
   L5_TTPC2_cAD : 3.633 Hz
   L5_UTPC_cAD : 5.942 Hz
   L6_BPC_cAD : 1.955 Hz
   L6_BP_bAC : 2.528 Hz
   L6_BP_bIR : 0.092 Hz
   L6_BP_bNA : 6.175 Hz
   L6_BP_cAC : 7.241 Hz
   L6_BP_cNA : 8.192 Hz
   L6_BP_dST : 0.125 Hz
   L6_BTC_bAC : 3.467 Hz
   L6_BTC_cAC : 2.907 Hz
   L6_BTC_cNA : 2.692 Hz
   L6_ChC_cAC : 11.417 Hz
   L6_ChC_cNA : 29.111 Hz
   L6_ChC_dNA : 9.625 Hz
   L6_DBC_bAC : 5.806 Hz
   L6_DBC_bIR : 0.083 Hz
   L6_DBC_bNA : 0.333 Hz
   L6_DBC_bST : 0.056 Hz
   L6_DBC_cAC : 5.861 Hz
   L6_DBC_cIR : 0.125 Hz
   L6_DBC_cNA : 1.083 Hz
   L6_IPC_cAD : 2.646 Hz
   L6_LBC_bAC : 4.476 Hz
   L6_LBC_bIR : 1.011 Hz
   L6_LBC_bNA : 21.791 Hz
   L6_LBC_bST : 5.892 Hz
   L6_LBC_cNA : 23.829 Hz
   L6_LBC_cST : 6.099 Hz
   L6_MC_bAC : 0.030 Hz
   L6_MC_bIR : 0.006 Hz
   L6_MC_bNA : 0.060 Hz
   L6_MC_bST : 0.036 Hz
   L6_MC_cAC : 0.074 Hz
   L6_MC_cIR : 0.012 Hz
   L6_MC_cNA : 0.077 Hz
   L6_NBC_bAC : 5.393 Hz
   L6_NBC_bIR : 1.280 Hz
   L6_NBC_bST : 8.985 Hz
   L6_NBC_cAC : 8.776 Hz
   L6_NBC_cIR : 2.226 Hz
   L6_NBC_cNA : 19.018 Hz
   L6_NBC_cST : 10.919 Hz
   L6_NBC_dST : 12.071 Hz
   L6_NGC_bNA : 6.125 Hz
   L6_NGC_cAC : 7.750 Hz
   L6_NGC_cNA : 9.508 Hz
   L6_NGC_cST : 0.208 Hz
   L6_SBC_bNA : 13.979 Hz
   L6_SBC_cAC : 14.559 Hz
   L6_SBC_dNA : 10.140 Hz
   L6_TPC_L1_cAD : 2.419 Hz
   L6_TPC_L4_cAD : 3.200 Hz
   L6_UTPC_cAD : 3.424 Hz
   ss_RTN_m : 11.466 Hz
   VPM_sTC : 2.906 Hz
   VPM_TC : 2.826 Hz
Saving output as ../data/v8_batch9/v8_batch9_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 69.60 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 285.67 s

Total time = 92733.21 s
Preparing spike data...
Plotting spike frequency...
