numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v8_batch7/v8_batch7_0_0_cfg.json
Loading file ../data/v8_batch7/v8_batch7_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py
Importing netParams from ../data/v8_batch7/v8_batch7_netParams.py

Start time:  2025-08-04 15:23:02.345309

Creating network of 210 cell populations on 128 hosts...
  Number of cells on node 12: 264 
  Number of cells on node 13: 264 
  Number of cells on node 127: 263 
  Number of cells on node 8: 264 
  Number of cells on node 10: 264 
  Number of cells on node 56: 264 
  Number of cells on node 16: 264 
  Number of cells on node 15: 264 
  Number of cells on node 14: 264 
  Number of cells on node 20: 264 
  Number of cells on node 3: 264 
  Number of cells on node 11: 264 
  Number of cells on node 60: 264 
  Number of cells on node 23: 264 
  Number of cells on node 96: 263 
  Number of cells on node 26: 264 
  Number of cells on node 27: 264 
  Number of cells on node 21: 264 
  Number of cells on node 24: 264 
  Number of cells on node 9: 264 
  Number of cells on node 29: 264 
  Number of cells on node 32: 264 
  Number of cells on node 22: 264 
  Number of cells on node 28: 264 
  Number of cells on node 31: 264 
  Number of cells on node 19: 264 
  Number of cells on node 25: 264 
  Number of cells on node 36: 264 
  Number of cells on node 115: 263 
  Number of cells on node 37: 264 
  Number of cells on node 39: 264 
  Number of cells on node 44: 264 
  Number of cells on node 38: 264 
  Number of cells on node 45: 264 
  Number of cells on node 42: 264 
  Number of cells on node 43: 264 
  Number of cells on node 49: 264 
  Number of cells on node 33: 264 
  Number of cells on node 34: 264 
  Number of cells on node 51: 264 
  Number of cells on node 86: 263 
  Number of cells on node 48: 264 
  Number of cells on node 50: 264 
  Number of cells on node 47: 264 
  Number of cells on node 41: 264 
  Number of cells on node 55: 264 
  Number of cells on node 46: 264 
  Number of cells on node 59: 264 
  Number of cells on node 61: 264 
  Number of cells on node 52: 264 
  Number of cells on node 58: 264 
  Number of cells on node 62: 264 
  Number of cells on node 54: 264 
  Number of cells on node 63: 264 
  Number of cells on node 57: 264 
  Number of cells on node 66: 264 
  Number of cells on node 68: 264 
  Number of cells on node 1: 264 
  Number of cells on node 70: 264 
  Number of cells on node 72: 264 
  Number of cells on node 69: 264 
  Number of cells on node 65: 264 
  Number of cells on node 74: 263 
  Number of cells on node 76: 263 
  Number of cells on node 67: 264 
  Number of cells on node 77: 263 
  Number of cells on node 40: 264 
  Number of cells on node 80: 263 
  Number of cells on node 73: 264 
  Number of cells on node 35: 264 
  Number of cells on node 81: 263 
  Number of cells on node 78: 263 
  Number of cells on node 75: 263 
  Number of cells on node 84: 263 
  Number of cells on node 87: 263 
  Number of cells on node 85: 263 
  Number of cells on node 94: 263 
  Number of cells on node 110: 263 
  Number of cells on node 88: 263 
  Number of cells on node 90: 263 
  Number of cells on node 79: 263 
  Number of cells on node 64: 264 
  Number of cells on node 92: 263 
  Number of cells on node 53: 264 
  Number of cells on node 91: 263 
  Number of cells on node 109: 263 
  Number of cells on node 98: 263 
  Number of cells on node 100: 263 
  Number of cells on node 101: 263 
  Number of cells on node 82: 263 
  Number of cells on node 89: 263 
  Number of cells on node 102: 263 
  Number of cells on node 97: 263 
  Number of cells on node 103: 263 
  Number of cells on node 95: 263 
  Number of cells on node 106: 263 
  Number of cells on node 30: 264 
  Number of cells on node 93: 263 
  Number of cells on node 83: 263 
  Number of cells on node 112: 263 
  Number of cells on node 105: 263 
  Number of cells on node 104: 263 
  Number of cells on node 108: 263 
  Number of cells on node 116: 263 
  Number of cells on node 99: 263 
  Number of cells on node 17: 264 
  Number of cells on node 107: 263 
  Number of cells on node 114: 263 
  Number of cells on node 113: 263 
  Number of cells on node 119: 263 
  Number of cells on node 122: 263 
  Number of cells on node 124: 263 
  Number of cells on node 0: 264 
  Done; cell creation time = 17.05 s.
Making connections...
  Number of cells on node 71: 264 
  Number of cells on node 118: 263 
  Number of cells on node 117: 263 
  Number of cells on node 125: 263 
  Number of cells on node 121: 263 
  Number of cells on node 18: 264 
  Number of cells on node 111: 263 
  Number of cells on node 120: 263 
  Number of cells on node 126: 263 
  Number of cells on node 4: 264 
  Number of cells on node 123: 263 
  Number of cells on node 6: 264 
  Number of cells on node 5: 264 
  Number of cells on node 7: 264 
  Number of cells on node 2: 264 
  Number of connections on node 75: 70517 
  Number of synaptic contacts on node 75: 369817 
  Number of connections on node 107: 69832 
  Number of synaptic contacts on node 107: 363084 
  Number of connections on node 67: 70021 
  Number of synaptic contacts on node 67: 366835 
  Number of connections on node 123: 70214 
  Number of synaptic contacts on node 123: 369605 
  Number of connections on node 121: 70327 
  Number of synaptic contacts on node 121: 368471 
  Number of connections on node 81: 71515 
  Number of synaptic contacts on node 81: 376704 
  Number of connections on node 89: 70247 
  Number of synaptic contacts on node 89: 368759 
  Number of connections on node 65: 69343 
  Number of synaptic contacts on node 65: 363514 
  Number of connections on node 105: 70078 
  Number of synaptic contacts on node 105: 366179 
  Number of connections on node 32: 69005 
  Number of synaptic contacts on node 32: 362890 
  Number of connections on node 83: 70021 
  Number of synaptic contacts on node 83: 366742 
  Number of connections on node 26: 70944 
  Number of synaptic contacts on node 26: 374756 
  Number of connections on node 97: 71133 
  Number of synaptic contacts on node 97: 371921 
  Number of connections on node 48: 70529 
  Number of synaptic contacts on node 48: 369449 
  Number of connections on node 99: 71212 
  Number of synaptic contacts on node 99: 373588 
  Number of connections on node 0: 69271 
  Number of synaptic contacts on node 0: 362382 
  Number of connections on node 8: 70899 
  Number of synaptic contacts on node 8: 373242 
  Number of connections on node 113: 70048 
  Number of synaptic contacts on node 113: 367715 
  Number of connections on node 34: 69084 
  Number of synaptic contacts on node 34: 362062 
  Number of connections on node 115: 69860 
  Number of synaptic contacts on node 115: 362179 
  Number of connections on node 16: 71002 
  Number of synaptic contacts on node 16: 372740 
  Number of connections on node 56: 69090 
  Number of synaptic contacts on node 56: 360130 
  Number of connections on node 73: 70673 
  Number of synaptic contacts on node 73: 371982 
  Number of connections on node 24: 72318 
  Number of synaptic contacts on node 24: 381332 
  Number of connections on node 10: 71954 
  Number of synaptic contacts on node 10: 377466 
  Number of connections on node 58: 70841 
  Number of synaptic contacts on node 58: 369407 
  Number of connections on node 2: 70235 
  Number of synaptic contacts on node 2: 369327 
  Number of connections on node 50: 70555 
  Number of synaptic contacts on node 50: 368960 
  Number of connections on node 40: 70402 
  Number of synaptic contacts on node 40: 367917 
  Number of connections on node 42: 70655 
  Number of synaptic contacts on node 42: 370536 
  Number of connections on node 120: 70537 
  Number of synaptic contacts on node 120: 369150 
  Number of connections on node 18: 68848 
  Number of synaptic contacts on node 18: 360423 
  Number of connections on node 112: 70364 
  Number of synaptic contacts on node 112: 369525 
  Number of connections on node 98: 70630 
  Number of synaptic contacts on node 98: 369373 
  Number of connections on node 19: 70482 
  Number of synaptic contacts on node 19: 373395 
  Number of connections on node 66: 70008 
  Number of synaptic contacts on node 66: 366391 
  Number of connections on node 57: 70910 
  Number of synaptic contacts on node 57: 370233 
  Number of connections on node 41: 70628 
  Number of synaptic contacts on node 41: 368334 
  Number of connections on node 90: 70385 
  Number of synaptic contacts on node 90: 370044 
  Number of connections on node 33: 70832 
  Number of synaptic contacts on node 33: 369829 
  Number of connections on node 1: 67845 
  Number of synaptic contacts on node 1: 357647 
  Number of connections on node 3: 68361 
  Number of synaptic contacts on node 3: 359429 
  Number of connections on node 122: 70297 
  Number of synaptic contacts on node 122: 368726 
  Number of connections on node 64: 69495 
  Number of synaptic contacts on node 64: 364712 
  Number of connections on node 35: 70855 
  Number of synaptic contacts on node 35: 370583 
  Number of connections on node 80: 69723 
  Number of synaptic contacts on node 80: 367127 
  Number of connections on node 17: 71751 
  Number of synaptic contacts on node 17: 377451 
  Number of connections on node 106: 68987 
  Number of synaptic contacts on node 106: 361181 
  Number of connections on node 72: 72087 
  Number of synaptic contacts on node 72: 377325 
  Number of connections on node 49: 69438 
  Number of synaptic contacts on node 49: 365268 
  Number of connections on node 96: 70031 
  Number of synaptic contacts on node 96: 365318 
  Number of connections on node 114: 69098 
  Number of synaptic contacts on node 114: 360910 
  Number of connections on node 51: 71732 
  Number of synaptic contacts on node 51: 373591 
  Number of connections on node 9: 70283 
  Number of synaptic contacts on node 9: 370673 
  Number of connections on node 104: 71361 
  Number of synaptic contacts on node 104: 373090 
  Number of connections on node 88: 70387 
  Number of synaptic contacts on node 88: 370029 
  Number of connections on node 74: 69676 
  Number of synaptic contacts on node 74: 366646 
  Number of connections on node 82: 70149 
  Number of synaptic contacts on node 82: 365796 
  Number of connections on node 43: 70181 
  Number of synaptic contacts on node 43: 368996 
  Number of connections on node 11: 70027 
  Number of synaptic contacts on node 11: 369346 
  Number of connections on node 27: 71530 
  Number of synaptic contacts on node 27: 374216 
  Number of connections on node 25: 70657 
  Number of synaptic contacts on node 25: 370066 
  Number of connections on node 91: 71838 
  Number of synaptic contacts on node 91: 378080 
  Number of connections on node 59: 71100 
  Number of synaptic contacts on node 59: 373570 
  Number of connections on node 93: 72737 
  Number of synaptic contacts on node 93: 381689 
  Number of connections on node 85: 68524 
  Number of synaptic contacts on node 85: 359425 
  Number of connections on node 117: 69154 
  Number of synaptic contacts on node 117: 362287 
  Number of connections on node 119: 69099 
  Number of synaptic contacts on node 119: 361921 
  Number of connections on node 95: 69245 
  Number of synaptic contacts on node 95: 362854 
  Number of connections on node 69: 72235 
  Number of synaptic contacts on node 69: 379572 
  Number of connections on node 127: 71118 
  Number of synaptic contacts on node 127: 369784 
  Number of connections on node 79: 69617 
  Number of synaptic contacts on node 79: 364472 
  Number of connections on node 111: 70892 
  Number of synaptic contacts on node 111: 369537 
  Number of connections on node 125: 73581 
  Number of synaptic contacts on node 125: 385301 
  Number of connections on node 28: 71725 
  Number of synaptic contacts on node 28: 374264 
  Number of connections on node 103: 70942 
  Number of synaptic contacts on node 103: 371145 
  Number of connections on node 71: 70240 
  Number of synaptic contacts on node 71: 369098 
  Number of connections on node 36: 71283 
  Number of synaptic contacts on node 36: 372512 
  Number of connections on node 6: 70261 
  Number of synaptic contacts on node 6: 366743 
  Number of connections on node 14: 70489 
  Number of synaptic contacts on node 14: 370278 
  Number of connections on node 60: 69536 
  Number of synaptic contacts on node 60: 363401 
  Number of connections on node 20: 72974 
  Number of synaptic contacts on node 20: 381834 
  Number of connections on node 77: 69542 
  Number of synaptic contacts on node 77: 362881 
  Number of connections on node 4: 68907 
  Number of synaptic contacts on node 4: 362731 
  Number of connections on node 38: 70492 
  Number of synaptic contacts on node 38: 369171 
  Number of connections on node 12: 69788 
  Number of synaptic contacts on node 12: 367287 
  Number of connections on node 87: 70989 
  Number of synaptic contacts on node 87: 371893 
  Number of connections on node 44: 71408 
  Number of synaptic contacts on node 44: 374045 
  Number of connections on node 52: 71302 
  Number of synaptic contacts on node 52: 375235 
  Number of connections on node 109: 69524 
  Number of synaptic contacts on node 109: 364514 
  Number of connections on node 62: 69942 
  Number of synaptic contacts on node 62: 364871 
  Number of connections on node 46: 70556 
  Number of synaptic contacts on node 46: 370693 
  Number of connections on node 22: 71245 
  Number of synaptic contacts on node 22: 375877 
  Number of connections on node 54: 70314 
  Number of synaptic contacts on node 54: 369470 
  Number of connections on node 101: 70434 
  Number of synaptic contacts on node 101: 371170 
  Number of connections on node 30: 67096 
  Number of synaptic contacts on node 30: 352855 
  Number of connections on node 92: 70025 
  Number of synaptic contacts on node 92: 366982 
  Number of connections on node 86: 67742 
  Number of synaptic contacts on node 86: 354316 
  Number of connections on node 55: 70363 
  Number of synaptic contacts on node 55: 367657 
  Number of connections on node 126: 70808 
  Number of synaptic contacts on node 126: 373814 
  Number of connections on node 37: 70904 
  Number of synaptic contacts on node 37: 369693 
  Number of connections on node 7: 68582 
  Number of synaptic contacts on node 7: 358892 
  Number of connections on node 108: 69928 
  Number of synaptic contacts on node 108: 365963 
  Number of connections on node 102: 69539 
  Number of synaptic contacts on node 102: 363635 
  Number of connections on node 124: 72329 
  Number of synaptic contacts on node 124: 378992 
  Number of connections on node 116: 70680 
  Number of synaptic contacts on node 116: 370435 
  Number of connections on node 13: 68755 
  Number of synaptic contacts on node 13: 360073 
  Number of connections on node 68: 70065 
  Number of synaptic contacts on node 68: 362815 
  Number of connections on node 45: 70230 
  Number of synaptic contacts on node 45: 366889 
  Number of connections on node 118: 69819 
  Number of synaptic contacts on node 118: 366789 
  Number of connections on node 100: 70501 
  Number of synaptic contacts on node 100: 368057 
  Number of connections on node 94: 69210 
  Number of synaptic contacts on node 94: 361107 
  Number of connections on node 84: 68479 
  Number of synaptic contacts on node 84: 359120 
  Number of connections on node 15: 71771 
  Number of synaptic contacts on node 15: 378537 
  Number of connections on node 70: 68954 
  Number of synaptic contacts on node 70: 360911 
  Number of connections on node 5: 69285 
  Number of synaptic contacts on node 5: 362316 
  Number of connections on node 39: 69125 
  Number of synaptic contacts on node 39: 362222 
  Number of connections on node 53: 71940 
  Number of synaptic contacts on node 53: 376491 
  Number of connections on node 47: 70096 
  Number of synaptic contacts on node 47: 365429 
  Number of connections on node 76: 71261 
  Number of synaptic contacts on node 76: 372256 
  Number of connections on node 61: 68225 
  Number of synaptic contacts on node 61: 359882 
  Number of connections on node 110: 69717 
  Number of synaptic contacts on node 110: 365084 
  Number of connections on node 78: 71854 
  Number of synaptic contacts on node 78: 377371 
  Number of connections on node 29: 71767 
  Number of synaptic contacts on node 29: 375565 
  Number of connections on node 23: 70437 
  Number of synaptic contacts on node 23: 373006 
  Number of connections on node 21: 70840 
  Number of synaptic contacts on node 21: 372194 
  Number of connections on node 31: 70209 
  Number of synaptic contacts on node 31: 368925 
  Number of connections on node 63: 69794 
  Number of synaptic contacts on node 63: 362772 
  Done; cell connection time = 13424.97 s.
Adding stims...
  Number of stims on node 2: 2603 
  Number of stims on node 40: 2583 
  Number of stims on node 64: 2583 
  Number of stims on node 35: 2583 
  Number of stims on node 3: 2603 
  Number of stims on node 112: 2603 
  Number of stims on node 26: 2583 
  Number of stims on node 115: 2593 
  Number of stims on node 104: 2603 
  Number of stims on node 24: 2583 
  Number of stims on node 121: 2593 
  Number of stims on node 107: 2603 
  Number of stims on node 39: 2583 
  Number of stims on node 99: 2603 
  Number of stims on node 27: 2583 
  Number of stims on node 91: 2582 
  Number of stims on node 56: 2583 
  Number of stims on node 12: 2603 
  Number of stims on node 113: 2603 
  Number of stims on node 48: 2583 
  Number of stims on node 42: 2583 
  Number of stims on node 16: 2603 
  Number of stims on node 17: 2603 
  Number of stims on node 114: 2593 
  Number of stims on node 0: 2603 
  Number of stims on node 120: 2593 
  Number of stims on node 123: 2593 
  Number of stims on node 98: 2603 
  Number of stims on node 105: 2603 
  Number of stims on node 89: 2582 
  Number of stims on node 97: 2603 
  Number of stims on node 9: 2603 
  Number of stims on node 57: 2583 
  Number of stims on node 106: 2603 
  Number of stims on node 6: 2603 
  Number of stims on node 41: 2583 
  Number of stims on node 43: 2583 
  Number of stims on node 10: 2603 
  Number of stims on node 34: 2583 
  Number of stims on node 50: 2583 
  Number of stims on node 73: 2583 
  Number of stims on node 82: 2582 
  Number of stims on node 127: 2593 
  Number of stims on node 111: 2603 
  Number of stims on node 58: 2583 
  Number of stims on node 51: 2583 
  Number of stims on node 66: 2583 
  Number of stims on node 122: 2593 
  Number of stims on node 90: 2582 
  Number of stims on node 80: 2582 
  Number of stims on node 81: 2582 
  Number of stims on node 33: 2583 
  Number of stims on node 101: 2603 
  Number of stims on node 95: 2603 
  Number of stims on node 49: 2583 
  Number of stims on node 25: 2583 
  Number of stims on node 88: 2582 
  Number of stims on node 8: 2603 
  Number of stims on node 119: 2593 
  Number of stims on node 75: 2582 
  Number of stims on node 67: 2583 
  Number of stims on node 96: 2603 
  Number of stims on node 32: 2583 
  Number of stims on node 103: 2603 
  Number of stims on node 19: 2603 
  Number of stims on node 30: 2583 
  Number of stims on node 5: 2603 
  Number of stims on node 109: 2603 
  Number of stims on node 65: 2583 
  Number of stims on node 1: 2603 
  Number of stims on node 83: 2582 
  Number of stims on node 37: 2583 
  Number of stims on node 74: 2582 
  Number of stims on node 18: 2603 
  Number of stims on node 7: 2603 
  Number of stims on node 72: 2583 
  Number of stims on node 79: 2582 
  Number of stims on node 59: 2583 
  Number of stims on node 102: 2603 
  Number of stims on node 118: 2593 
  Number of stims on node 53: 2583 
  Number of stims on node 77: 2582 
  Number of stims on node 125: 2593 
  Number of stims on node 15: 2603 
  Number of stims on node 94: 2603 
  Number of stims on node 13: 2603 
  Number of stims on node 85: 2582 
  Number of stims on node 23: 2583 
  Number of stims on node 93: 2582 
  Number of stims on node 117: 2593 
  Number of stims on node 28: 2583 
  Number of stims on node 11: 2603 
  Number of stims on node 124: 2593 
  Number of stims on node 69: 2583 
  Number of stims on node 44: 2583 
  Number of stims on node 110: 2603 
  Number of stims on node 55: 2583 
  Number of stims on node 31: 2583 
  Number of stims on node 22: 2583 
  Number of stims on node 108: 2603 
  Number of stims on node 116: 2593 
  Number of stims on node 126: 2593 
  Number of stims on node 71: 2583 
  Number of stims on node 70: 2583 
  Number of stims on node 36: 2583 
  Number of stims on node 52: 2583 
  Number of stims on node 87: 2582 
  Number of stims on node 68: 2583 
  Number of stims on node 46: 2583 
  Number of stims on node 14: 2603 
  Number of stims on node 4: 2603 
  Number of stims on node 47: 2583 
  Number of stims on node 62: 2583 
  Number of stims on node 86: 2582 
  Number of stims on node 61: 2583 
  Number of stims on node 100: 2603 
  Number of stims on node 76: 2582 
  Number of stims on node 78: 2582 
  Number of stims on node 45: 2583 
  Number of stims on node 54: 2583 
  Number of stims on node 63: 2583 
  Number of stims on node 38: 2583 
  Number of stims on node 29: 2583 
  Number of stims on node 21: 2583 
  Number of stims on node 20: 2583 
  Number of stims on node 60: 2583 
  Number of stims on node 84: 2582 
  Number of stims on node 92: 2582 
  Done; cell stims creation time = 8.71 s.
Recording 7 traces of 1 types on node 3
Recording 12 traces of 1 types on node 124
Recording 7 traces of 1 types on node 5
Recording 7 traces of 1 types on node 108
Recording 13 traces of 1 types on node 107
Recording 5 traces of 1 types on node 35
Recording 5 traces of 1 types on node 23
Recording 4 traces of 1 types on node 28
Recording 13 traces of 1 types on node 60
Recording 12 traces of 1 types on node 91
Recording 9 traces of 1 types on node 57
Recording 9 traces of 1 types on node 99
Recording 8 traces of 1 types on node 16
Recording 5 traces of 1 types on node 17
Recording 5 traces of 1 types on node 33
Recording 6 traces of 1 types on node 59
Recording 8 traces of 1 types on node 117
Recording 7 traces of 1 types on node 7
Recording 9 traces of 1 types on node 98
Recording 8 traces of 1 types on node 10
Recording 4 traces of 1 types on node 32
Recording 9 traces of 1 types on node 100
Recording 7 traces of 1 types on node 89
Recording 10 traces of 1 types on node 121
Recording 10 traces of 1 types on node 118
Recording 8 traces of 1 types on node 2
Recording 8 traces of 1 types on node 31
Recording 9 traces of 1 types on node 26
Recording 9 traces of 1 types on node 116
Recording 5 traces of 1 types on node 20
Recording 7 traces of 1 types on node 96
Recording 5 traces of 1 types on node 40
Recording 12 traces of 1 types on node 83
Recording 5 traces of 1 types on node 48
Recording 9 traces of 1 types on node 1
Recording 8 traces of 1 types on node 62
Recording 8 traces of 1 types on node 11
Recording 8 traces of 1 types on node 56
Recording 7 traces of 1 types on node 71
Recording 5 traces of 1 types on node 55
Recording 12 traces of 1 types on node 114
Recording 7 traces of 1 types on node 18
Recording 8 traces of 1 types on node 104
Recording 8 traces of 1 types on node 113
Recording 2 traces of 1 types on node 39
Recording 10 traces of 1 types on node 86
Recording 7 traces of 1 types on node 97
Recording 5 traces of 1 types on node 58
Recording 9 traces of 1 types on node 27
Recording 7 traces of 1 types on node 29
Recording 9 traces of 1 types on node 115
Recording 9 traces of 1 types on node 64
Recording 6 traces of 1 types on node 90
Recording 8 traces of 1 types on node 6
Recording 10 traces of 1 types on node 82
Recording 6 traces of 1 types on node 30
Recording 12 traces of 1 types on node 0
Recording 5 traces of 1 types on node 73
Recording 9 traces of 1 types on node 44
Recording 5 traces of 1 types on node 50
Recording 2 traces of 1 types on node 34
Recording 9 traces of 1 types on node 54
Recording 8 traces of 1 types on node 87
Recording 6 traces of 1 types on node 46
Recording 9 traces of 1 types on node 101
Recording 8 traces of 1 types on node 85
Recording 11 traces of 1 types on node 105
Recording 7 traces of 1 types on node 14
Recording 8 traces of 1 types on node 74
Recording 10 traces of 1 types on node 119
Recording 4 traces of 1 types on node 41
Recording 12 traces of 1 types on node 112
Recording 3 traces of 1 types on node 37
Recording 10 traces of 1 types on node 4
Recording 4 traces of 1 types on node 13
Recording 7 traces of 1 types on node 94
Recording 7 traces of 1 types on node 106
Recording 6 traces of 1 types on node 78
Recording 8 traces of 1 types on node 123
Recording 3 traces of 1 types on node 122
Recording 5 traces of 1 types on node 95
Recording 4 traces of 1 types on node 25
Recording 7 traces of 1 types on node 127
Recording 6 traces of 1 types on node 67
Recording 7 traces of 1 types on node 9
Recording 10 traces of 1 types on node 88
Recording 8 traces of 1 types on node 8
Recording 7 traces of 1 types on node 110
Recording 9 traces of 1 types on node 80
Recording 8 traces of 1 types on node 79
Recording 6 traces of 1 types on node 24
Recording 8 traces of 1 types on node 45
Recording 4 traces of 1 types on node 69
Recording 7 traces of 1 types on node 53
Recording 13 traces of 1 types on node 109
Recording 9 traces of 1 types on node 75
Recording 5 traces of 1 types on node 120
Recording 7 traces of 1 types on node 63
Recording 9 traces of 1 types on node 61
Recording 7 traces of 1 types on node 102
Recording 4 traces of 1 types on node 47
Recording 8 traces of 1 types on node 77
Recording 7 traces of 1 types on node 22
Recording 6 traces of 1 types on node 81
Recording 5 traces of 1 types on node 70
Recording 5 traces of 1 types on node 15
Recording 10 traces of 1 types on node 126
Recording 7 traces of 1 types on node 19
Recording 6 traces of 1 types on node 49
Recording 6 traces of 1 types on node 42
Recording 8 traces of 1 types on node 12
Recording 8 traces of 1 types on node 111
Recording 7 traces of 1 types on node 66
Recording 3 traces of 1 types on node 43
Recording 10 traces of 1 types on node 52
Recording 9 traces of 1 types on node 103
Recording 6 traces of 1 types on node 72
Recording 2 traces of 1 types on node 92
Recording 5 traces of 1 types on node 65
Recording 9 traces of 1 types on node 68
Recording 6 traces of 1 types on node 36
Recording 7 traces of 1 types on node 125
Recording 7 traces of 1 types on node 84
Recording 10 traces of 1 types on node 51
Recording 8 traces of 1 types on node 38
Recording 7 traces of 1 types on node 76
Recording 5 traces of 1 types on node 21
Recording 9 traces of 1 types on node 93
0.0s

Running simulation using NEURON for 12000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
  Done; run time = 82541.65 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 17.54 s.

Analyzing...
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

There was an exception in prepareSpikeData()

Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...


There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...


There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

There was an exception in prepareSpikeData()

Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...
Preparing spike data...

There was an exception in prepareSpikeData()

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()Preparing spike data...

There was an exception in prepareSpikeData()

Preparing spike data...

There was an exception in prepareSpikeData()
Preparing spike data...

There was an exception in prepareSpikeData()
  Cells: 33738
  Connections: 0 (0.00 per cell)
  Spikes: 1039041 (2.57 Hz)
  Simulated time: 12.0 s; 128 workers
  Run time: 82541.65 s

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()

There was an exception in prepareSpikeHist()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
Plotting spike frequency...

There was an exception in plotSpikeFreq()
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.002 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.000 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 1.194 Hz
   L23_BP_bIR : 0.604 Hz
   L23_BP_bNA : 2.405 Hz
   L23_BP_cAC : 2.369 Hz
   L23_BP_cNA : 5.458 Hz
   L23_BP_dST : 0.583 Hz
   L23_BTC_bAC : 0.039 Hz
   L23_BTC_bIR : 0.024 Hz
   L23_BTC_bNA : 0.065 Hz
   L23_BTC_cAC : 0.039 Hz
   L23_BTC_cNA : 0.069 Hz
   L23_ChC_cAC : 0.268 Hz
   L23_ChC_cNA : 0.181 Hz
   L23_ChC_dNA : 0.122 Hz
   L23_DBC_bAC : 0.500 Hz
   L23_DBC_bIR : 0.065 Hz
   L23_DBC_bNA : 0.242 Hz
   L23_DBC_cAC : 0.202 Hz
   L23_LBC_bAC : 0.029 Hz
   L23_LBC_bNA : 0.522 Hz
   L23_LBC_cAC : 0.063 Hz
   L23_LBC_cNA : 0.065 Hz
   L23_LBC_cST : 0.220 Hz
   L23_LBC_dNA : 0.378 Hz
   L23_MC_bAC : 0.008 Hz
   L23_MC_bNA : 0.025 Hz
   L23_MC_cAC : 0.023 Hz
   L23_MC_cNA : 0.023 Hz
   L23_MC_dNA : 0.008 Hz
   L23_NBC_bAC : 0.018 Hz
   L23_NBC_bNA : 0.278 Hz
   L23_NBC_cAC : 0.067 Hz
   L23_NBC_cIR : 0.028 Hz
   L23_NBC_cNA : 0.060 Hz
   L23_NBC_dNA : 0.131 Hz
   L23_NGC_bNA : 0.117 Hz
   L23_NGC_cAC : 0.100 Hz
   L23_NGC_cNA : 0.091 Hz
   L23_NGC_cST : 0.067 Hz
   L23_PC_cAD : 0.335 Hz
   L23_SBC_bNA : 0.399 Hz
   L23_SBC_cAC : 0.550 Hz
   L23_SBC_dNA : 0.181 Hz
   L4_BP_bAC : 8.333 Hz
   L4_BP_bIR : 0.083 Hz
   L4_BP_bNA : 4.792 Hz
   L4_BP_cAC : 5.083 Hz
   L4_BP_cNA : 9.583 Hz
   L4_BP_dST : 0.083 Hz
   L4_BTC_bAC : 4.292 Hz
   L4_BTC_bIR : 0.083 Hz
   L4_BTC_bST : 0.167 Hz
   L4_BTC_cAC : 0.481 Hz
   L4_BTC_cNA : 0.194 Hz
   L4_BTC_dNA : 0.125 Hz
   L4_ChC_cAC : 6.139 Hz
   L4_ChC_cNA : 2.889 Hz
   L4_ChC_dNA : 0.417 Hz
   L4_DBC_bAC : 5.188 Hz
   L4_DBC_bIR : 0.077 Hz
   L4_DBC_bNA : 0.208 Hz
   L4_DBC_bST : 0.042 Hz
   L4_DBC_cAC : 0.583 Hz
   L4_DBC_cIR : 0.071 Hz
   L4_DBC_cNA : 0.125 Hz
   L4_LBC_cAC : 1.981 Hz
   L4_LBC_cNA : 2.839 Hz
   L4_LBC_cST : 1.656 Hz
   L4_LBC_dNA : 5.024 Hz
   L4_LBC_dST : 1.185 Hz
   L4_MC_bAC : 0.008 Hz
   L4_MC_bNA : 0.021 Hz
   L4_MC_cAC : 0.043 Hz
   L4_MC_cNA : 0.046 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 2.792 Hz
   L4_NBC_cIR : 0.533 Hz
   L4_NBC_cNA : 2.506 Hz
   L4_NBC_dNA : 2.359 Hz
   L4_NGC_bNA : 0.500 Hz
   L4_NGC_cAC : 0.917 Hz
   L4_NGC_cNA : 0.500 Hz
   L4_NGC_cST : 0.083 Hz
   L4_PC_cAD : 1.487 Hz
   L4_SBC_bNA : 5.758 Hz
   L4_SBC_cAC : 5.841 Hz
   L4_SBC_dNA : 5.216 Hz
   L4_SP_cAD : 2.842 Hz
   L4_SS_cAD : 3.148 Hz
   L5_BP_bAC : 2.611 Hz
   L5_BP_bIR : 0.150 Hz
   L5_BP_bNA : 8.528 Hz
   L5_BP_cAC : 9.944 Hz
   L5_BP_cNA : 13.550 Hz
   L5_BP_dST : 0.167 Hz
   L5_BTC_bAC : 5.115 Hz
   L5_BTC_cAC : 1.397 Hz
   L5_BTC_cNA : 1.718 Hz
   L5_ChC_cAC : 15.917 Hz
   L5_ChC_cNA : 18.786 Hz
   L5_ChC_dNA : 8.717 Hz
   L5_DBC_bAC : 3.222 Hz
   L5_DBC_bIR : 0.083 Hz
   L5_DBC_bNA : 0.556 Hz
   L5_DBC_bST : 0.157 Hz
   L5_DBC_cAC : 1.546 Hz
   L5_DBC_cIR : 0.132 Hz
   L5_DBC_cNA : 0.963 Hz
   L5_LBC_bAC : 6.035 Hz
   L5_LBC_cAC : 9.853 Hz
   L5_LBC_cIR : 1.474 Hz
   L5_LBC_cNA : 18.333 Hz
   L5_LBC_cST : 11.561 Hz
   L5_LBC_dNA : 19.757 Hz
   L5_LBC_dST : 8.718 Hz
   L5_MC_bAC : 0.336 Hz
   L5_MC_bIR : 0.059 Hz
   L5_MC_bST : 0.062 Hz
   L5_MC_cAC : 0.762 Hz
   L5_MC_cNA : 0.380 Hz
   L5_MC_cST : 0.057 Hz
   L5_MC_dNA : 0.068 Hz
   L5_NBC_bAC : 4.435 Hz
   L5_NBC_bIR : 0.762 Hz
   L5_NBC_bST : 3.867 Hz
   L5_NBC_cAC : 13.127 Hz
   L5_NBC_cIR : 4.440 Hz
   L5_NBC_cNA : 18.207 Hz
   L5_NBC_cST : 7.071 Hz
   L5_NBC_dST : 7.885 Hz
   L5_NGC_bNA : 6.750 Hz
   L5_NGC_cAC : 9.000 Hz
   L5_NGC_cNA : 12.583 Hz
   L5_NGC_cST : 0.250 Hz
   L5_SBC_bNA : 5.944 Hz
   L5_SBC_cAC : 10.176 Hz
   L5_SBC_dNA : 13.929 Hz
   L5_STPC_cAD : 4.270 Hz
   L5_TTPC1_cAD : 3.423 Hz
   L5_TTPC2_cAD : 3.639 Hz
   L5_UTPC_cAD : 5.971 Hz
   L6_BPC_cAD : 1.951 Hz
   L6_BP_bAC : 2.542 Hz
   L6_BP_bIR : 0.092 Hz
   L6_BP_bNA : 5.996 Hz
   L6_BP_cAC : 6.719 Hz
   L6_BP_cNA : 7.558 Hz
   L6_BP_dST : 0.083 Hz
   L6_BTC_bAC : 3.750 Hz
   L6_BTC_cAC : 2.917 Hz
   L6_BTC_cNA : 2.700 Hz
   L6_ChC_cAC : 11.278 Hz
   L6_ChC_cNA : 30.264 Hz
   L6_ChC_dNA : 9.875 Hz
   L6_DBC_bAC : 5.806 Hz
   L6_DBC_bIR : 0.075 Hz
   L6_DBC_bNA : 0.444 Hz
   L6_DBC_bST : 0.056 Hz
   L6_DBC_cAC : 2.944 Hz
   L6_DBC_cIR : 0.083 Hz
   L6_DBC_cNA : 1.083 Hz
   L6_IPC_cAD : 2.644 Hz
   L6_LBC_bAC : 4.479 Hz
   L6_LBC_bIR : 1.027 Hz
   L6_LBC_bNA : 21.554 Hz
   L6_LBC_bST : 5.904 Hz
   L6_LBC_cNA : 22.484 Hz
   L6_LBC_cST : 6.308 Hz
   L6_MC_bAC : 0.030 Hz
   L6_MC_bIR : 0.006 Hz
   L6_MC_bNA : 0.060 Hz
   L6_MC_bST : 0.024 Hz
   L6_MC_cAC : 0.089 Hz
   L6_MC_cIR : 0.012 Hz
   L6_MC_cNA : 0.089 Hz
   L6_NBC_bAC : 5.577 Hz
   L6_NBC_bIR : 1.226 Hz
   L6_NBC_bST : 7.395 Hz
   L6_NBC_cAC : 8.158 Hz
   L6_NBC_cIR : 2.649 Hz
   L6_NBC_cNA : 19.881 Hz
   L6_NBC_cST : 11.205 Hz
   L6_NBC_dST : 10.869 Hz
   L6_NGC_bNA : 6.875 Hz
   L6_NGC_cAC : 7.333 Hz
   L6_NGC_cNA : 9.667 Hz
   L6_NGC_cST : 0.083 Hz
   L6_SBC_bNA : 14.316 Hz
   L6_SBC_cAC : 15.156 Hz
   L6_SBC_dNA : 10.197 Hz
   L6_TPC_L1_cAD : 2.412 Hz
   L6_TPC_L4_cAD : 3.202 Hz
   L6_UTPC_cAD : 3.431 Hz
   ss_RTN_m : 11.508 Hz
   VPM_sTC : 2.820 Hz
   VPM_TC : 2.761 Hz
Saving output as ../data/v8_batch7/v8_batch7_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 70.22 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 231.06 s

Total time = 96448.74 s
Preparing spike data...
Plotting spike frequency...
