numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch2/v8_batch2_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py

Start time:  2025-04-26 22:34:22.247548
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py
Importing netParams from ../data/v8_batch2/v8_batch2_netParams.py

Creating network of 210 cell populations on 128 hosts...
  Number of cells on node 20: 264 
  Number of cells on node 42: 264 
  Number of cells on node 32: 264 
  Number of cells on node 52: 264 
  Number of cells on node 93: 263 
  Number of cells on node 16: 264 
  Number of cells on node 111: 263 
  Number of cells on node 11: 264 
  Number of cells on node 94: 263 
  Number of cells on node 67: 264 
  Number of cells on node 65: 264 
  Number of cells on node 91: 263 
  Number of cells on node 12: 264 
  Number of cells on node 89: 263 
  Number of cells on node 36: 264 
  Number of cells on node 119: 263 
  Number of cells on node 55: 264 
  Number of cells on node 37: 264 
  Number of cells on node 39: 264 
  Number of cells on node 60: 264 
  Number of cells on node 69: 264 
  Number of cells on node 97: 263 
  Number of cells on node 75: 263 
  Number of cells on node 77: 263 
  Number of cells on node 126: 263 
  Number of cells on node 117: 263 
  Number of cells on node 51: 264 
  Number of cells on node 73: 264 
  Number of cells on node 25: 264 
  Number of cells on node 82: 263 
  Number of cells on node 18: 264 
  Number of cells on node 31: 264 
  Number of cells on node 44: 264 
  Number of cells on node 88: 263 
  Number of cells on node 95: 263 
  Number of cells on node 120: 263 
  Number of cells on node 105: 263 
  Number of cells on node 106: 263 
  Number of cells on node 26: 264 
  Number of cells on node 96: 263 
  Number of cells on node 64: 264 
  Number of cells on node 80: 263 
  Number of cells on node 10: 264 
  Number of cells on node 50: 264 
  Number of cells on node 125: 263 
  Number of cells on node 98: 263 
  Number of cells on node 114: 263 
  Number of cells on node 115: 263 
  Number of cells on node 45: 264 
  Number of cells on node 127: 263 
  Number of cells on node 23: 264 
  Number of cells on node 72: 264 
  Number of cells on node 107: 263 
  Number of cells on node 112: 263 
  Number of cells on node 118: 263 
  Number of cells on node 71: 264 
  Number of cells on node 85: 263 
  Number of cells on node 21: 264 
  Number of cells on node 58: 264 
  Number of cells on node 30: 264 
  Number of cells on node 83: 263 
  Number of cells on node 70: 264 
  Number of cells on node 35: 264 
  Number of cells on node 27: 264 
  Number of cells on node 49: 264 
  Number of cells on node 74: 263 
  Number of cells on node 43: 264 
  Number of cells on node 66: 264 
  Number of cells on node 3: 264 
  Number of cells on node 46: 264 
  Number of cells on node 38: 264 
  Number of cells on node 108: 263 
  Number of cells on node 68: 264 
  Number of cells on node 54: 264 
  Number of cells on node 122: 263 
  Number of cells on node 48: 264 
  Number of cells on node 59: 264 
  Number of cells on node 90: 263 
  Number of cells on node 79: 263 
  Number of cells on node 22: 264 
  Number of cells on node 109: 263 
  Number of cells on node 7: 264 
  Number of cells on node 15: 264 
  Number of cells on node 110: 263 
  Number of cells on node 99: 263 
  Number of cells on node 102: 263 
  Number of cells on node 40: 264 
  Number of cells on node 56: 264 
  Number of cells on node 41: 264 
  Number of cells on node 121: 263 
  Number of cells on node 57: 264 
  Number of cells on node 62: 264 
  Number of cells on node 63: 264 
  Number of cells on node 103: 263 
  Number of cells on node 92: 263 
  Number of cells on node 100: 263 
  Number of cells on node 81: 263 
  Number of cells on node 33: 264 
  Number of cells on node 47: 264 
  Number of cells on node 0: 264 
  Number of cells on node 86: 263 
  Number of cells on node 1: 264 
  Number of cells on node 24: 264 
  Number of cells on node 9: 264 
  Number of cells on node 13: 264 
  Number of cells on node 29: 264 
  Number of cells on node 28: 264 
  Number of cells on node 84: 263 
  Number of cells on node 17: 264 
  Number of cells on node 34: 264 
  Number of cells on node 4: 264 
  Number of cells on node 8: 264 
  Number of cells on node 101: 263 
  Number of cells on node 6: 264 
  Number of cells on node 123: 263 
  Number of cells on node 87: 263 
  Number of cells on node 76: 263 
  Number of cells on node 14: 264 
  Number of cells on node 116: 263 
  Number of cells on node 19: 264 
  Number of cells on node 53: 264 
  Number of cells on node 78: 263 
  Number of cells on node 104: 263 
  Number of cells on node 113: 263 
  Number of cells on node 124: 263 
  Number of cells on node 2: 264 
  Number of cells on node 61: 264 
  Number of cells on node 5: 264 
  Done; cell creation time = 26.44 s.
Making connections...
  Number of connections on node 30: 68857 
  Number of synaptic contacts on node 30: 361406 
  Number of connections on node 60: 68757 
  Number of synaptic contacts on node 60: 359181 
  Number of connections on node 52: 69795 
  Number of synaptic contacts on node 52: 367099 
  Number of connections on node 6: 70521 
  Number of synaptic contacts on node 6: 370398 
  Number of connections on node 44: 69867 
  Number of synaptic contacts on node 44: 366442 
  Number of connections on node 12: 70722 
  Number of synaptic contacts on node 12: 373073 
  Number of connections on node 14: 69907 
  Number of synaptic contacts on node 14: 365896 
  Number of connections on node 40: 69972 
  Number of synaptic contacts on node 40: 365420 
  Number of connections on node 22: 69876 
  Number of synaptic contacts on node 22: 368142 
  Number of connections on node 85: 68763 
  Number of synaptic contacts on node 85: 360839 
  Number of connections on node 20: 69390 
  Number of synaptic contacts on node 20: 364285 
  Number of connections on node 26: 70784 
  Number of synaptic contacts on node 26: 372329 
  Number of connections on node 48: 69892 
  Number of synaptic contacts on node 48: 367697 
  Number of connections on node 58: 70714 
  Number of synaptic contacts on node 58: 371435 
  Number of connections on node 127: 70975 
  Number of synaptic contacts on node 127: 372726 
  Number of connections on node 24: 68818 
  Number of synaptic contacts on node 24: 360144 
  Number of connections on node 28: 70262 
  Number of synaptic contacts on node 28: 369702 
  Number of connections on node 117: 70231 
  Number of synaptic contacts on node 117: 368535 
  Number of connections on node 56: 71468 
  Number of synaptic contacts on node 56: 375633 
  Number of connections on node 16: 69815 
  Number of synaptic contacts on node 16: 367021 
  Number of connections on node 8: 70719 
  Number of synaptic contacts on node 8: 371403 
  Number of connections on node 79: 70025 
  Number of synaptic contacts on node 79: 367463 
  Number of connections on node 69: 70644 
  Number of synaptic contacts on node 69: 372046 
  Number of connections on node 10: 70145 
  Number of synaptic contacts on node 10: 365832 
  Number of connections on node 18: 70422 
  Number of synaptic contacts on node 18: 369464 
  Number of connections on node 0: 68221 
  Number of synaptic contacts on node 0: 358521 
  Number of connections on node 93: 69223 
  Number of synaptic contacts on node 93: 361724 
  Number of connections on node 34: 70614 
  Number of synaptic contacts on node 34: 370138 
  Number of connections on node 46: 70182 
  Number of synaptic contacts on node 46: 367661 
  Number of connections on node 38: 68327 
  Number of synaptic contacts on node 38: 358938 
  Number of connections on node 111: 69572 
  Number of synaptic contacts on node 111: 365556 
  Number of connections on node 103: 70956 
  Number of synaptic contacts on node 103: 370951 
  Number of connections on node 119: 68923 
  Number of synaptic contacts on node 119: 362821 
  Number of connections on node 4: 70567 
  Number of synaptic contacts on node 4: 368494 
  Number of connections on node 36: 68731 
  Number of synaptic contacts on node 36: 359442 
  Number of connections on node 62: 70097 
  Number of synaptic contacts on node 62: 367664 
  Number of connections on node 77: 72888 
  Number of synaptic contacts on node 77: 380919 
  Number of connections on node 42: 72583 
  Number of synaptic contacts on node 42: 377434 
  Number of connections on node 123: 71210 
  Number of synaptic contacts on node 123: 373812 
  Number of connections on node 32: 71117 
  Number of synaptic contacts on node 32: 373403 
  Number of connections on node 50: 69096 
  Number of synaptic contacts on node 50: 359756 
  Number of connections on node 54: 69610 
  Number of synaptic contacts on node 54: 363574 
  Number of connections on node 71: 69092 
  Number of synaptic contacts on node 71: 361832 
  Number of connections on node 67: 69339 
  Number of synaptic contacts on node 67: 364940 
  Number of connections on node 109: 69208 
  Number of synaptic contacts on node 109: 361719 
  Number of connections on node 125: 69135 
  Number of synaptic contacts on node 125: 364928 
  Number of connections on node 95: 69364 
  Number of synaptic contacts on node 95: 361049 
  Number of connections on node 101: 69163 
  Number of synaptic contacts on node 101: 362614 
  Number of connections on node 91: 69422 
  Number of synaptic contacts on node 91: 367144 
  Number of connections on node 75: 69092 
  Number of synaptic contacts on node 75: 361725 
  Number of connections on node 113: 70507 
  Number of synaptic contacts on node 113: 370020 
  Number of connections on node 89: 71361 
  Number of synaptic contacts on node 89: 373030 
  Number of connections on node 87: 71539 
  Number of synaptic contacts on node 87: 376360 
  Number of connections on node 83: 67724 
  Number of synaptic contacts on node 83: 356077 
  Number of connections on node 2: 71190 
  Number of synaptic contacts on node 2: 374272 
  Number of connections on node 81: 71221 
  Number of synaptic contacts on node 81: 371086 
  Number of connections on node 115: 69668 
  Number of synaptic contacts on node 115: 364932 
  Number of connections on node 65: 71312 
  Number of synaptic contacts on node 65: 375742 
  Number of connections on node 99: 69336 
  Number of synaptic contacts on node 99: 364709 
  Number of connections on node 107: 70224 
  Number of synaptic contacts on node 107: 365171 
  Number of connections on node 105: 69590 
  Number of synaptic contacts on node 105: 364897 
  Number of connections on node 97: 70188 
  Number of synaptic contacts on node 97: 365706 
  Number of connections on node 73: 71596 
  Number of synaptic contacts on node 73: 378473 
  Number of connections on node 121: 68661 
  Number of synaptic contacts on node 121: 357495 
  Number of connections on node 63: 70497 
  Number of synaptic contacts on node 63: 369211 
  Number of connections on node 37: 70048 
  Number of synaptic contacts on node 37: 367476 
  Number of connections on node 47: 69211 
  Number of synaptic contacts on node 47: 362284 
  Number of connections on node 39: 69392 
  Number of synaptic contacts on node 39: 363523 
  Number of connections on node 53: 70623 
  Number of synaptic contacts on node 53: 369657 
  Number of connections on node 45: 70378 
  Number of synaptic contacts on node 45: 367201 
  Number of connections on node 15: 71130 
  Number of synaptic contacts on node 15: 372656 
  Number of connections on node 55: 70665 
  Number of synaptic contacts on node 55: 371007 
  Number of connections on node 51: 68593 
  Number of synaptic contacts on node 51: 359060 
  Number of connections on node 31: 70282 
  Number of synaptic contacts on node 31: 369556 
  Number of connections on node 21: 70701 
  Number of synaptic contacts on node 21: 369335 
  Number of connections on node 23: 70737 
  Number of synaptic contacts on node 23: 369589 
  Number of connections on node 29: 69866 
  Number of synaptic contacts on node 29: 362890 
  Number of connections on node 118: 69985 
  Number of synaptic contacts on node 118: 365777 
  Number of connections on node 7: 70428 
  Number of synaptic contacts on node 7: 368523 
  Number of connections on node 5: 69549 
  Number of synaptic contacts on node 5: 363018 
  Number of connections on node 108: 70685 
  Number of synaptic contacts on node 108: 370042 
  Number of connections on node 61: 70365 
  Number of synaptic contacts on node 61: 367509 
  Number of connections on node 110: 68464 
  Number of synaptic contacts on node 110: 359586 
  Number of connections on node 92: 70916 
  Number of synaptic contacts on node 92: 370587 
  Number of connections on node 13: 70261 
  Number of synaptic contacts on node 13: 369937 
  Number of connections on node 76: 68812 
  Number of synaptic contacts on node 76: 364948 
  Number of connections on node 25: 69104 
  Number of synaptic contacts on node 25: 361249 
  Number of connections on node 57: 70469 
  Number of synaptic contacts on node 57: 367540 
  Number of connections on node 3: 69687 
  Number of synaptic contacts on node 3: 364188 
  Number of connections on node 11: 70702 
  Number of synaptic contacts on node 11: 371264 
  Number of connections on node 33: 71232 
  Number of synaptic contacts on node 33: 374038 
  Number of connections on node 126: 69028 
  Number of synaptic contacts on node 126: 363627 
  Number of connections on node 86: 71895 
  Number of synaptic contacts on node 86: 377116 
  Number of connections on node 9: 69035 
  Number of synaptic contacts on node 9: 362247 
  Number of connections on node 84: 67741 
  Number of synaptic contacts on node 84: 355960 
  Number of connections on node 59: 70392 
  Number of synaptic contacts on node 59: 368199 
  Number of connections on node 43: 68149 
  Number of synaptic contacts on node 43: 357028 
  Number of connections on node 17: 68951 
  Number of synaptic contacts on node 17: 361511 
  Number of connections on node 102: 70096 
  Number of synaptic contacts on node 102: 367024 
  Number of connections on node 116: 69373 
  Number of synaptic contacts on node 116: 363101 
  Number of connections on node 41: 70159 
  Number of synaptic contacts on node 41: 366310 
  Number of connections on node 80: 69431 
  Number of synaptic contacts on node 80: 363819 
  Number of connections on node 27: 69348 
  Number of synaptic contacts on node 27: 363044 
  Number of connections on node 68: 70173 
  Number of synaptic contacts on node 68: 367519 
  Number of connections on node 120: 69727 
  Number of synaptic contacts on node 120: 366952 
  Number of connections on node 78: 69735 
  Number of synaptic contacts on node 78: 366800 
  Number of connections on node 66: 69980 
  Number of synaptic contacts on node 66: 369672 
  Number of connections on node 104: 69158 
  Number of synaptic contacts on node 104: 362583 
  Number of connections on node 35: 69632 
  Number of synaptic contacts on node 35: 364600 
  Number of connections on node 72: 70741 
  Number of synaptic contacts on node 72: 368788 
  Number of connections on node 49: 70655 
  Number of synaptic contacts on node 49: 371202 
  Number of connections on node 19: 71118 
  Number of synaptic contacts on node 19: 371492 
  Number of connections on node 64: 70258 
  Number of synaptic contacts on node 64: 369120 
  Number of connections on node 114: 68152 
  Number of synaptic contacts on node 114: 359268 
  Number of connections on node 124: 69628 
  Number of synaptic contacts on node 124: 363741 
  Number of connections on node 106: 70194 
  Number of synaptic contacts on node 106: 368761 
  Number of connections on node 112: 68702 
  Number of synaptic contacts on node 112: 360575 
  Number of connections on node 98: 71984 
  Number of synaptic contacts on node 98: 379190 
  Number of connections on node 96: 68529 
  Number of synaptic contacts on node 96: 358924 
  Number of connections on node 90: 70982 
  Number of synaptic contacts on node 90: 370692 
  Number of connections on node 88: 70063 
  Number of synaptic contacts on node 88: 367147 
  Number of connections on node 74: 69574 
  Number of synaptic contacts on node 74: 365597 
  Number of connections on node 100: 70005 
  Number of synaptic contacts on node 100: 368551 
  Number of connections on node 1: 69376 
  Number of synaptic contacts on node 1: 362336 
  Number of connections on node 82: 71190 
  Number of synaptic contacts on node 82: 372431 
  Number of connections on node 122: 70989 
  Number of synaptic contacts on node 122: 375411 
  Number of connections on node 94: 70332 
  Number of synaptic contacts on node 94: 367436 
  Number of connections on node 70: 70539 
  Number of synaptic contacts on node 70: 368867 
  Done; cell connection time = 6619.63 s.
Adding stims...
  Number of stims on node 36: 2583 
  Number of stims on node 29: 2583 
  Number of stims on node 60: 2583 
  Number of stims on node 115: 2593 
  Number of stims on node 123: 2593 
  Number of stims on node 50: 2583 
  Number of stims on node 77: 2582 
  Number of stims on node 18: 2603 
  Number of stims on node 116: 2593 
  Number of stims on node 72: 2583 
  Number of stims on node 28: 2583 
  Number of stims on node 44: 2583 
  Number of stims on node 111: 2603 
  Number of stims on node 90: 2582 
  Number of stims on node 124: 2593 
  Number of stims on node 100: 2603 
  Number of stims on node 21: 2583 
  Number of stims on node 97: 2603 
  Number of stims on node 10: 2603 
  Number of stims on node 42: 2583 
  Number of stims on node 69: 2583 
  Number of stims on node 48: 2583 
  Number of stims on node 85: 2582 
  Number of stims on node 4: 2603 
  Number of stims on node 22: 2583 
  Number of stims on node 43: 2583 
  Number of stims on node 89: 2582 
  Number of stims on node 104: 2603 
  Number of stims on node 25: 2583 
  Number of stims on node 2: 2603 
  Number of stims on node 114: 2593 
  Number of stims on node 67: 2583 
  Number of stims on node 32: 2583 
  Number of stims on node 37: 2583 
  Number of stims on node 26: 2583 
  Number of stims on node 46: 2583 
  Number of stims on node 0: 2603 
  Number of stims on node 45: 2583 
  Number of stims on node 83: 2582 
  Number of stims on node 34: 2583 
  Number of stims on node 119: 2593 
  Number of stims on node 84: 2582 
  Number of stims on node 101: 2603 
  Number of stims on node 11: 2603 
  Number of stims on node 47: 2583 
  Number of stims on node 105: 2603 
  Number of stims on node 5: 2603 
  Number of stims on node 8: 2603 
  Number of stims on node 107: 2603 
  Number of stims on node 113: 2603 
  Number of stims on node 108: 2603 
  Number of stims on node 76: 2582 
  Number of stims on node 109: 2603 
  Number of stims on node 93: 2582 
  Number of stims on node 3: 2603 
  Number of stims on node 41: 2583 
  Number of stims on node 87: 2582 
  Number of stims on node 82: 2582 
  Number of stims on node 110: 2603 
  Number of stims on node 126: 2593 
  Number of stims on node 118: 2593 
  Number of stims on node 6: 2603 
  Number of stims on node 9: 2603 
  Number of stims on node 121: 2593 
  Number of stims on node 33: 2583 
  Number of stims on node 24: 2583 
  Number of stims on node 99: 2603 
  Number of stims on node 61: 2583 
  Number of stims on node 70: 2583 
  Number of stims on node 49: 2583 
  Number of stims on node 12: 2603 
  Number of stims on node 96: 2603 
  Number of stims on node 125: 2593 
  Number of stims on node 52: 2583 
  Number of stims on node 31: 2583 
  Number of stims on node 79: 2582 
  Number of stims on node 120: 2593 
  Number of stims on node 39: 2583 
  Number of stims on node 91: 2582 
  Number of stims on node 81: 2582 
  Number of stims on node 53: 2583 
  Number of stims on node 30: 2583 
  Number of stims on node 17: 2603 
  Number of stims on node 122: 2593 
  Number of stims on node 95: 2603 
  Number of stims on node 80: 2582 
  Number of stims on node 40: 2583 
  Number of stims on node 38: 2583 
  Number of stims on node 13: 2603 
  Number of stims on node 127: 2593 
  Number of stims on node 74: 2582 
  Number of stims on node 1: 2603 
  Number of stims on node 117: 2593 
  Number of stims on node 20: 2583 
  Number of stims on node 92: 2582 
  Number of stims on node 65: 2583 
  Number of stims on node 23: 2583 
  Number of stims on node 59: 2583 
  Number of stims on node 7: 2603 
  Number of stims on node 98: 2603 
  Number of stims on node 68: 2583 
  Number of stims on node 64: 2583 
  Number of stims on node 14: 2603 
  Number of stims on node 78: 2582 
  Number of stims on node 86: 2582 
  Number of stims on node 55: 2583 
  Number of stims on node 56: 2583 
  Number of stims on node 57: 2583 
  Number of stims on node 58: 2583 
  Number of stims on node 63: 2583 
  Number of stims on node 112: 2603 
  Number of stims on node 88: 2582 
  Number of stims on node 106: 2603 
  Number of stims on node 73: 2583 
  Number of stims on node 66: 2583 
  Number of stims on node 94: 2603 
  Number of stims on node 75: 2582 
  Number of stims on node 62: 2583 
  Number of stims on node 19: 2603 
  Number of stims on node 51: 2583 
  Number of stims on node 103: 2603 
  Number of stims on node 16: 2603 
  Number of stims on node 102: 2603 
  Number of stims on node 54: 2583 
  Number of stims on node 71: 2583 
  Number of stims on node 15: 2603 
  Number of stims on node 27: 2583 
  Number of stims on node 35: 2583 
  Done; cell stims creation time = 8.37 s.
Recording 5 traces of 1 types on node 95
Recording 6 traces of 1 types on node 24
Recording 7 traces of 1 types on node 97
Recording 5 traces of 1 types on node 40
Recording 4 traces of 1 types on node 25
Recording 8 traces of 1 types on node 111
Recording 6 traces of 1 types on node 78
Recording 7 traces of 1 types on node 96
Recording 4 traces of 1 types on node 41
Recording 9 traces of 1 types on node 64
Recording 5 traces of 1 types on node 70
Recording 7 traces of 1 types on node 125
Recording 6 traces of 1 types on node 46
Recording 7 traces of 1 types on node 22
Recording 12 traces of 1 types on node 91
Recording 10 traces of 1 types on node 86
Recording 8 traces of 1 types on node 16
Recording 9 traces of 1 types on node 99
Recording 7 traces of 1 types on node 108
Recording 10 traces of 1 types on node 51
Recording 5 traces of 1 types on node 21
Recording 6 traces of 1 types on node 67
Recording 5 traces of 1 types on node 120
Recording 13 traces of 1 types on node 109
Recording 6 traces of 1 types on node 72
Recording 8 traces of 1 types on node 123
Recording 7 traces of 1 types on node 5
Recording 9 traces of 1 types on node 80
Recording 9 traces of 1 types on node 26
Recording 7 traces of 1 types on node 84
Recording 5 traces of 1 types on node 55
Recording 13 traces of 1 types on node 107
Recording 9 traces of 1 types on node 101
Recording 7 traces of 1 types on node 66
Recording 9 traces of 1 types on node 44
Recording 3 traces of 1 types on node 43
Recording 10 traces of 1 types on node 119
Recording 9 traces of 1 types on node 75
Recording 7 traces of 1 types on node 106
Recording 5 traces of 1 types on node 33
Recording 6 traces of 1 types on node 90
Recording 12 traces of 1 types on node 124
Recording 5 traces of 1 types on node 50
Recording 2 traces of 1 types on node 34
Recording 9 traces of 1 types on node 57
Recording 7 traces of 1 types on node 18
Recording 8 traces of 1 types on node 38
Recording 8 traces of 1 types on node 79
Recording 7 traces of 1 types on node 94
Recording 9 traces of 1 types on node 116
Recording 8 traces of 1 types on node 85
Recording 10 traces of 1 types on node 82
Recording 4 traces of 1 types on node 47
Recording 2 traces of 1 types on node 92
Recording 10 traces of 1 types on node 4
Recording 6 traces of 1 types on node 36
Recording 2 traces of 1 types on node 39
Recording 11 traces of 1 types on node 105
Recording 8 traces of 1 types on node 77
Recording 6 traces of 1 types on node 42
Recording 9 traces of 1 types on node 54
Recording 4 traces of 1 types on node 13
Recording 12 traces of 1 types on node 112
Recording 7 traces of 1 types on node 29
Recording 5 traces of 1 types on node 65
Recording 6 traces of 1 types on node 30
Recording 8 traces of 1 types on node 11
Recording 9 traces of 1 types on node 115
Recording 12 traces of 1 types on node 0
Recording 7 traces of 1 types on node 14
Recording 3 traces of 1 types on node 37
Recording 7 traces of 1 types on node 76
Recording 8 traces of 1 types on node 74
Recording 10 traces of 1 types on node 88
Recording 4 traces of 1 types on node 28
Recording 8 traces of 1 types on node 56
Recording 5 traces of 1 types on node 17
Recording 4 traces of 1 types on node 32
Recording 13 traces of 1 types on node 60
Recording 8 traces of 1 types on node 87
Recording 7 traces of 1 types on node 89
Recording 12 traces of 1 types on node 114
Recording 5 traces of 1 types on node 73
Recording 8 traces of 1 types on node 10
Recording 7 traces of 1 types on node 63
Recording 7 traces of 1 types on node 19
Recording 4 traces of 1 types on node 69
Recording 10 traces of 1 types on node 126
Recording 8 traces of 1 types on node 45
Recording 7 traces of 1 types on node 3
Recording 10 traces of 1 types on node 52
Recording 9 traces of 1 types on node 61
Recording 5 traces of 1 types on node 15
Recording 10 traces of 1 types on node 118
Recording 10 traces of 1 types on node 121
Recording 8 traces of 1 types on node 117
Recording 7 traces of 1 types on node 127
Recording 6 traces of 1 types on node 49
Recording 8 traces of 1 types on node 2
Recording 5 traces of 1 types on node 58
Recording 6 traces of 1 types on node 59
Recording 7 traces of 1 types on node 71
Recording 8 traces of 1 types on node 31
Recording 8 traces of 1 types on node 6
Recording 9 traces of 1 types on node 98
Recording 7 traces of 1 types on node 102
Recording 8 traces of 1 types on node 113
Recording 9 traces of 1 types on node 100
Recording 9 traces of 1 types on node 27
Recording 5 traces of 1 types on node 35
Recording 5 traces of 1 types on node 20
Recording 7 traces of 1 types on node 7
Recording 8 traces of 1 types on node 12
Recording 9 traces of 1 types on node 68
Recording 5 traces of 1 types on node 48
Recording 8 traces of 1 types on node 104
Recording 6 traces of 1 types on node 81
Recording 7 traces of 1 types on node 110
Recording 8 traces of 1 types on node 8
Recording 7 traces of 1 types on node 9
Recording 7 traces of 1 types on node 53
Recording 8 traces of 1 types on node 62
Recording 12 traces of 1 types on node 83
Recording 9 traces of 1 types on node 93
Recording 9 traces of 1 types on node 1
Recording 3 traces of 1 types on node 122
Recording 5 traces of 1 types on node 23
Recording 9 traces of 1 types on node 103
0.0s

Running simulation using NEURON for 12000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
  Done; run time = 81447.77 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 15.82 s.

Analyzing...
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba83bfc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba83bf80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacc9600>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacc96c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacc96c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba8b8340>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba8b8080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba8b8080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf56380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf562c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf562c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf0ec80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf0ed40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf0ed40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155484a884c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155484a88640>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155484a88640>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baedef80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baedef40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baedef40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e71c740>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e71cd00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e71cd00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba77fac0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba77fb80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba77fb80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b7f4580>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b7f4700>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b7f4700>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554869fb180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554869fb300>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554869fb300>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548af1da00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548af1db80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548af1db80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba83bf80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b4f6200>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b4f6380>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b4f6380>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baff5d80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baff5e40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baff5e40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548ce04c40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548ce049c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548ce049c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15549024ed80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15549024ec80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15549024ec80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b321b00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b321100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b321100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554978d0c40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554978d0e40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554978d0e40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155496128280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155496128580>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155496128580>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb015cc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb015d80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb015d80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155489d7e700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155489d7e880>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155489d7e880>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf60e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf60f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf60f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafebd40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafebe00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafebe00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554746dd040>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554746dd480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554746dd480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15547b46d080>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15547b46de40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15547b46de40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b170100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b170280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b170280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b047100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b047280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b047280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155486866dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155486866f40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155486866f40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e48f640>)Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e3d06c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e3d0c80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e3d0c80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554958e54c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554958e5340>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554958e5340>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155481da9e40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155481da9cc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155481da9cc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafc2a80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafc2b80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafc2b80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baceb380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baceb2c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baceb2c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb55ec40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb55ed00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb55ed00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e75e700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e75ed00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e75ed00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554735d4700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554735d4880>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554735d4880>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b23bb00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b23bc80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b23bc80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba72ffc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba72f0c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba72f0c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155472c69600>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155472c69c00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155472c69c00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b542540>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b5426c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b5426c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554567f24c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554567f2640>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554567f2640>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b366700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b366880>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b366880>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15544accb340>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15544accb4c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15544accb4c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4eb180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4eb0c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4eb0c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafdec00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafded00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafded00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554badc11c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554badc1040>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554badc1040>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155498810b40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155498810d40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155498810d40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b30e2c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b30e040>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b30e040>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba58ae80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba58af80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba58af80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafa2140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafa20c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafa20c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155472ee6640>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155472ee6c00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155472ee6c00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548d8ad240>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548d8ad0c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548d8ad0c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e688740>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e688d40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e688d40>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad05e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad05f40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad05f40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548aefc280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548aefc400>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548aefc400>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba55f1c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba55f100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba55f100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1553e2823c40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1553e2823dc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1553e2823dc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b370300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b370480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b370480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baa877c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baa878c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baa878c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4b0140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4b00c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4b00c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba80f340>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba80f280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba80f280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548af45280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548af45400>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548af45400>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b046b00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b046c80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b046c80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad2d140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad2d080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad2d080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e7377c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e737dc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e737dc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf8c9c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf8cac0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf8cac0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad0f800>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad0fd00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad0fd00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb04acc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb04ad80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb04ad80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba9ba580>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba9ba240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba9ba240>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15547b857ac0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15547b8575c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15547b8575c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad1b580>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad1b640>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad1b640>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155497e0a440>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155497e0a5c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155497e0a5c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba558cc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba558f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba558f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b04d300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b04d480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b04d480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548afc0b40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548afc0240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548afc0240>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba6fd380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba6fd080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba6fd080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554973a3c40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554973a3dc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554973a3dc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155490027740>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155490027ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155490027ec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bae8a100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bae8a080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bae8a080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4271c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba427100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba427100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554b9b85d40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554b9b85ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554b9b85ec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad644c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad645c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad645c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5a41c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5a4100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5a4100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548afafc40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548afaf240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548afaf240>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b034540>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b0346c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b0346c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554977a7bc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554977a7c00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554977a7c00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b312400>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba85ca80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba85cb40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba85cb40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b7a2200>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b7a2380>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b7a2380>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155494536800>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155494536900>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155494536900>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba57f140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba57f080>)
Plotting spike frequency...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5c9180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5c90c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5c90c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba87bfc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba87b0c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba87b0c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b278700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b278200>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b278200>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155495ba07c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155495ba0940>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155495ba0940>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155318f79840>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155318f797c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155318f797c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554682c7380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554682c7500>)
Plotting spike frequency...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf27d00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf27dc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf27dc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15549505c380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15549505c200>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15549505c200>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba575e40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba575f00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba575f00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b243400>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b243580>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b243580>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba64a140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba64a080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba64a080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf96e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf96f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf96f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb00d840>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb00dd40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb00dd40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155471b30e00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155471b30f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155471b30f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba3b0f00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba3b0080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba3b0080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba874fc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba8740c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba8740c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4fa300>)  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b312580>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b312580>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba7b1cc0>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba57f080>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554682c7500>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba7a9fc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7a90c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7a90c0>)
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba901fc0>)

  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4fa240>)
Plotting spike frequency...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7b1d80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7b1d80>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554498292c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba9010c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4fa240>)
Preparing spike data...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155449829540>)
Plotting spike frequency...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b25a300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b25a480>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba9010c0>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155449829540>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b25a480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba783e00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba783ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba783ec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba45a040>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba45a080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba45a080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b27c900>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b27ca80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b27ca80>)
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba67b1c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba67b100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba67b100>)

  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e48fc40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e48fc40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba472080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba8a02c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba8a0200>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba8a0200>)
Preparing spike data...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4720c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4720c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155492774e00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155492774f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155492774f80>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554968e0b40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554968e09c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554968e09c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba429140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba429080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba429080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba898dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba898e80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba898e80>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155497106780>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155497106900>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155497106900>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e69f480>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e69fc00>)
Plotting spike frequency...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba75ee80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba75ef80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba75ef80>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e69fc00>)
  Cells: 33738
  Connections: 0 (0.00 per cell)
  Spikes: 1039627 (2.57 Hz)
  Simulated time: 12.0 s; 128 workers
  Run time: 81447.77 s
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.002 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.006 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 1.222 Hz
   L23_BP_bIR : 0.396 Hz
   L23_BP_bNA : 1.988 Hz
   L23_BP_cAC : 2.881 Hz
   L23_BP_cNA : 3.104 Hz
   L23_BP_dST : 0.833 Hz
   L23_BTC_bAC : 0.056 Hz
   L23_BTC_bIR : 0.036 Hz
   L23_BTC_bNA : 0.058 Hz
   L23_BTC_cAC : 0.043 Hz
   L23_BTC_cNA : 0.056 Hz
   L23_ChC_cAC : 0.254 Hz
   L23_ChC_cNA : 0.188 Hz
   L23_ChC_dNA : 0.100 Hz
   L23_DBC_bAC : 0.451 Hz
   L23_DBC_bIR : 0.078 Hz
   L23_DBC_bNA : 0.344 Hz
   L23_DBC_cAC : 0.234 Hz
   L23_LBC_bAC : 0.033 Hz
   L23_LBC_bNA : 0.642 Hz
   L23_LBC_cAC : 0.071 Hz
   L23_LBC_cNA : 0.086 Hz
   L23_LBC_cST : 0.170 Hz
   L23_LBC_dNA : 0.394 Hz
   L23_MC_bAC : 0.000 Hz
   L23_MC_bNA : 0.025 Hz
   L23_MC_cAC : 0.026 Hz
   L23_MC_cNA : 0.025 Hz
   L23_MC_dNA : 0.000 Hz
   L23_NBC_bAC : 0.036 Hz
   L23_NBC_bNA : 0.278 Hz
   L23_NBC_cAC : 0.067 Hz
   L23_NBC_cIR : 0.042 Hz
   L23_NBC_cNA : 0.055 Hz
   L23_NBC_dNA : 0.125 Hz
   L23_NGC_bNA : 0.133 Hz
   L23_NGC_cAC : 0.083 Hz
   L23_NGC_cNA : 0.106 Hz
   L23_NGC_cST : 0.067 Hz
   L23_PC_cAD : 0.337 Hz
   L23_SBC_bNA : 0.476 Hz
   L23_SBC_cAC : 0.607 Hz
   L23_SBC_dNA : 0.187 Hz
   L4_BP_bAC : 8.333 Hz
   L4_BP_bIR : 6.083 Hz
   L4_BP_bNA : 5.083 Hz
   L4_BP_cAC : 5.417 Hz
   L4_BP_cNA : 8.167 Hz
   L4_BP_dST : 0.000 Hz
   L4_BTC_bAC : 1.333 Hz
   L4_BTC_bIR : 0.083 Hz
   L4_BTC_bST : 0.250 Hz
   L4_BTC_cAC : 0.667 Hz
   L4_BTC_cNA : 0.083 Hz
   L4_BTC_dNA : 0.125 Hz
   L4_ChC_cAC : 6.750 Hz
   L4_ChC_cNA : 3.472 Hz
   L4_ChC_dNA : 0.375 Hz
   L4_DBC_bAC : 1.812 Hz
   L4_DBC_bIR : 0.071 Hz
   L4_DBC_bNA : 0.167 Hz
   L4_DBC_bST : 0.083 Hz
   L4_DBC_cAC : 0.250 Hz
   L4_DBC_cIR : 0.071 Hz
   L4_DBC_cNA : 0.146 Hz
   L4_LBC_cAC : 2.330 Hz
   L4_LBC_cNA : 3.018 Hz
   L4_LBC_cST : 1.884 Hz
   L4_LBC_dNA : 4.524 Hz
   L4_LBC_dST : 1.435 Hz
   L4_MC_bAC : 0.008 Hz
   L4_MC_bNA : 0.021 Hz
   L4_MC_cAC : 0.044 Hz
   L4_MC_cNA : 0.056 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 3.467 Hz
   L4_NBC_cIR : 0.650 Hz
   L4_NBC_cNA : 2.985 Hz
   L4_NBC_dNA : 2.502 Hz
   L4_NGC_bNA : 0.500 Hz
   L4_NGC_cAC : 1.167 Hz
   L4_NGC_cNA : 0.528 Hz
   L4_NGC_cST : 0.083 Hz
   L4_PC_cAD : 1.491 Hz
   L4_SBC_bNA : 5.956 Hz
   L4_SBC_cAC : 5.814 Hz
   L4_SBC_dNA : 5.407 Hz
   L4_SP_cAD : 2.873 Hz
   L4_SS_cAD : 3.162 Hz
   L5_BP_bAC : 4.750 Hz
   L5_BP_bIR : 0.200 Hz
   L5_BP_bNA : 9.731 Hz
   L5_BP_cAC : 10.000 Hz
   L5_BP_cNA : 12.750 Hz
   L5_BP_dST : 0.139 Hz
   L5_BTC_bAC : 4.064 Hz
   L5_BTC_cAC : 1.487 Hz
   L5_BTC_cNA : 1.404 Hz
   L5_ChC_cAC : 15.393 Hz
   L5_ChC_cNA : 19.905 Hz
   L5_ChC_dNA : 8.050 Hz
   L5_DBC_bAC : 3.000 Hz
   L5_DBC_bIR : 0.083 Hz
   L5_DBC_bNA : 0.694 Hz
   L5_DBC_bST : 0.176 Hz
   L5_DBC_cAC : 1.685 Hz
   L5_DBC_cIR : 0.147 Hz
   L5_DBC_cNA : 0.843 Hz
   L5_LBC_bAC : 5.750 Hz
   L5_LBC_cAC : 10.453 Hz
   L5_LBC_cIR : 1.481 Hz
   L5_LBC_cNA : 19.023 Hz
   L5_LBC_cST : 11.419 Hz
   L5_LBC_dNA : 18.863 Hz
   L5_LBC_dST : 8.138 Hz
   L5_MC_bAC : 0.352 Hz
   L5_MC_bIR : 0.055 Hz
   L5_MC_bST : 0.073 Hz
   L5_MC_cAC : 0.762 Hz
   L5_MC_cNA : 0.188 Hz
   L5_MC_cST : 0.042 Hz
   L5_MC_dNA : 0.083 Hz
   L5_NBC_bAC : 5.042 Hz
   L5_NBC_bIR : 0.744 Hz
   L5_NBC_bST : 4.093 Hz
   L5_NBC_cAC : 13.019 Hz
   L5_NBC_cIR : 4.304 Hz
   L5_NBC_cNA : 19.047 Hz
   L5_NBC_cST : 7.029 Hz
   L5_NBC_dST : 7.724 Hz
   L5_NGC_bNA : 7.833 Hz
   L5_NGC_cAC : 9.417 Hz
   L5_NGC_cNA : 14.350 Hz
   L5_NGC_cST : 0.167 Hz
   L5_SBC_bNA : 6.824 Hz
   L5_SBC_cAC : 9.380 Hz
   L5_SBC_dNA : 15.024 Hz
   L5_STPC_cAD : 4.238 Hz
   L5_TTPC1_cAD : 3.408 Hz
   L5_TTPC2_cAD : 3.606 Hz
   L5_UTPC_cAD : 5.986 Hz
   L6_BPC_cAD : 1.950 Hz
   L6_BP_bAC : 2.736 Hz
   L6_BP_bIR : 0.100 Hz
   L6_BP_bNA : 5.693 Hz
   L6_BP_cAC : 6.522 Hz
   L6_BP_cNA : 7.350 Hz
   L6_BP_dST : 0.125 Hz
   L6_BTC_bAC : 4.508 Hz
   L6_BTC_cAC : 2.900 Hz
   L6_BTC_cNA : 3.083 Hz
   L6_ChC_cAC : 8.417 Hz
   L6_ChC_cNA : 29.069 Hz
   L6_ChC_dNA : 11.812 Hz
   L6_DBC_bAC : 3.750 Hz
   L6_DBC_bIR : 0.058 Hz
   L6_DBC_bNA : 0.639 Hz
   L6_DBC_bST : 0.056 Hz
   L6_DBC_cAC : 5.083 Hz
   L6_DBC_cIR : 0.250 Hz
   L6_DBC_cNA : 0.333 Hz
   L6_IPC_cAD : 2.647 Hz
   L6_LBC_bAC : 4.802 Hz
   L6_LBC_bIR : 1.001 Hz
   L6_LBC_bNA : 22.215 Hz
   L6_LBC_bST : 5.762 Hz
   L6_LBC_cNA : 22.837 Hz
   L6_LBC_cST : 6.717 Hz
   L6_MC_bAC : 0.039 Hz
   L6_MC_bIR : 0.010 Hz
   L6_MC_bNA : 0.060 Hz
   L6_MC_bST : 0.018 Hz
   L6_MC_cAC : 0.065 Hz
   L6_MC_cIR : 0.006 Hz
   L6_MC_cNA : 0.143 Hz
   L6_NBC_bAC : 5.435 Hz
   L6_NBC_bIR : 1.006 Hz
   L6_NBC_bST : 9.377 Hz
   L6_NBC_cAC : 8.692 Hz
   L6_NBC_cIR : 1.643 Hz
   L6_NBC_cNA : 19.640 Hz
   L6_NBC_cST : 10.355 Hz
   L6_NBC_dST : 11.637 Hz
   L6_NGC_bNA : 4.750 Hz
   L6_NGC_cAC : 7.542 Hz
   L6_NGC_cNA : 8.614 Hz
   L6_NGC_cST : 0.167 Hz
   L6_SBC_bNA : 12.670 Hz
   L6_SBC_cAC : 15.792 Hz
   L6_SBC_dNA : 9.439 Hz
   L6_TPC_L1_cAD : 2.409 Hz
   L6_TPC_L4_cAD : 3.195 Hz
   L6_UTPC_cAD : 3.413 Hz
   ss_RTN_m : 11.393 Hz
   VPM_sTC : 2.995 Hz
   VPM_TC : 2.743 Hz
Saving output as ../data/v8_batch2/v8_batch2_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 64.60 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 226.26 s

Total time = 88539.68 s
Preparing spike data...
Plotting spike frequency...
