numprocs=128

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading simConfig...
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v8_batch1/v8_batch1_0_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py

Start time:  2025-04-26 08:48:38.276875
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py
Importing netParams from ../data/v8_batch1/v8_batch1_netParams.py

Creating network of 210 cell populations on 128 hosts...
  Number of cells on node 6: 264 
  Number of cells on node 67: 264 
  Number of cells on node 34: 264 
  Number of cells on node 115: 263 
  Number of cells on node 25: 264 
  Number of cells on node 54: 264 
  Number of cells on node 21: 264 
  Number of cells on node 31: 264 
  Number of cells on node 37: 264 
  Number of cells on node 123: 263 
  Number of cells on node 91: 263 
  Number of cells on node 63: 264 
  Number of cells on node 47: 264 
  Number of cells on node 120: 263 
  Number of cells on node 75: 263 
  Number of cells on node 102: 263 
  Number of cells on node 50: 264 
  Number of cells on node 13: 264 
  Number of cells on node 24: 264 
  Number of cells on node 105: 263 
  Number of cells on node 14: 264 
  Number of cells on node 99: 263 
  Number of cells on node 55: 264 
  Number of cells on node 1: 264 
  Number of cells on node 78: 263 
  Number of cells on node 87: 263 
  Number of cells on node 42: 264 
  Number of cells on node 22: 264 
  Number of cells on node 5: 264 
  Number of cells on node 43: 264 
  Number of cells on node 97: 263 
  Number of cells on node 73: 264 
  Number of cells on node 48: 264 
  Number of cells on node 77: 263 
  Number of cells on node 109: 263 
  Number of cells on node 17: 264 
  Number of cells on node 82: 263 
  Number of cells on node 103: 263 
  Number of cells on node 127: 263 
  Number of cells on node 29: 264 
  Number of cells on node 112: 263 
  Number of cells on node 117: 263 
  Number of cells on node 36: 264 
  Number of cells on node 119: 263 
  Number of cells on node 39: 264 
  Number of cells on node 12: 264 
  Number of cells on node 49: 264 
  Number of cells on node 51: 264 
  Number of cells on node 98: 263 
  Number of cells on node 35: 264 
  Number of cells on node 20: 264 
  Number of cells on node 3: 264 
  Number of cells on node 79: 263 
  Number of cells on node 85: 263 
  Number of cells on node 40: 264 
  Number of cells on node 118: 263 
  Number of cells on node 38: 264 
  Number of cells on node 107: 263 
  Number of cells on node 15: 264 
  Number of cells on node 100: 263 
  Number of cells on node 121: 263 
  Number of cells on node 90: 263 
  Number of cells on node 110: 263 
  Number of cells on node 60: 264 
  Number of cells on node 84: 263 
  Number of cells on node 58: 264 
  Number of cells on node 89: 263 
  Number of cells on node 28: 264 
  Number of cells on node 81: 263 
  Number of cells on node 46: 264 
  Number of cells on node 19: 264 
  Number of cells on node 116: 263 
  Number of cells on node 86: 263 
  Number of cells on node 10: 264 
  Number of cells on node 32: 264 
  Number of cells on node 27: 264 
  Number of cells on node 106: 263 
  Number of cells on node 70: 264 
  Number of cells on node 30: 264 
  Number of cells on node 18: 264 
  Number of cells on node 76: 263 
  Number of cells on node 108: 263 
  Number of cells on node 8: 264 
  Number of cells on node 45: 264 
  Number of cells on node 72: 264 
  Number of cells on node 65: 264 
  Number of cells on node 126: 263 
  Number of cells on node 33: 264 
  Number of cells on node 56: 264 
  Number of cells on node 4: 264 
  Number of cells on node 125: 263 
  Number of cells on node 26: 264 
  Number of cells on node 2: 264 
  Number of cells on node 53: 264 
  Number of cells on node 94: 263 
  Number of cells on node 59: 264 
  Number of cells on node 68: 264 
  Number of cells on node 11: 264 
  Number of cells on node 23: 264 
  Number of cells on node 44: 264 
  Number of cells on node 96: 263 
  Number of cells on node 52: 264 
  Number of cells on node 74: 263 
  Number of cells on node 92: 263 
  Number of cells on node 41: 264 
  Number of cells on node 69: 264 
  Number of cells on node 104: 263 
  Number of cells on node 64: 264 
  Number of cells on node 122: 263 
  Number of cells on node 57: 264 
  Number of cells on node 66: 264 
  Number of cells on node 61: 264 
  Number of cells on node 124: 263 
  Number of cells on node 95: 263 
  Number of cells on node 93: 263 
  Number of cells on node 0: 264 
  Number of cells on node 114: 263 
  Number of cells on node 88: 263 
  Number of cells on node 111: 263 
  Number of cells on node 83: 263 
  Number of cells on node 101: 263 
  Number of cells on node 7: 264 
  Number of cells on node 71: 264 
  Number of cells on node 62: 264 
  Number of cells on node 9: 264 
  Number of cells on node 113: 263 
  Number of cells on node 80: 263 
  Number of cells on node 16: 264 
  Done; cell creation time = 31.63 s.
Making connections...
  Number of connections on node 51: 71605 
  Number of synaptic contacts on node 51: 372695 
  Number of connections on node 17: 71168 
  Number of synaptic contacts on node 17: 376436 
  Number of connections on node 27: 71480 
  Number of synaptic contacts on node 27: 373983 
  Number of connections on node 57: 71101 
  Number of synaptic contacts on node 57: 371559 
  Number of connections on node 11: 70312 
  Number of synaptic contacts on node 11: 367949 
  Number of connections on node 1: 68072 
  Number of synaptic contacts on node 1: 357571 
  Number of connections on node 41: 71121 
  Number of synaptic contacts on node 41: 370901 
  Number of connections on node 9: 70576 
  Number of synaptic contacts on node 9: 372228 
  Number of connections on node 3: 67767 
  Number of synaptic contacts on node 3: 355954 
  Number of connections on node 59: 70670 
  Number of synaptic contacts on node 59: 370745 
  Number of connections on node 19: 70192 
  Number of synaptic contacts on node 19: 369869 
  Number of connections on node 43: 70414 
  Number of synaptic contacts on node 43: 367400 
  Number of connections on node 35: 70774 
  Number of synaptic contacts on node 35: 369722 
  Number of connections on node 25: 70815 
  Number of synaptic contacts on node 25: 372483 
  Number of connections on node 33: 70760 
  Number of synaptic contacts on node 33: 368341 
  Number of connections on node 49: 69399 
  Number of synaptic contacts on node 49: 363046 
  Number of connections on node 16: 71089 
  Number of synaptic contacts on node 16: 373021 
  Number of connections on node 0: 69145 
  Number of synaptic contacts on node 0: 362583 
  Number of connections on node 18: 68951 
  Number of synaptic contacts on node 18: 360540 
  Number of connections on node 40: 70050 
  Number of synaptic contacts on node 40: 368698 
  Number of connections on node 26: 70864 
  Number of synaptic contacts on node 26: 371425 
  Number of connections on node 24: 71927 
  Number of synaptic contacts on node 24: 378374 
  Number of connections on node 32: 69222 
  Number of synaptic contacts on node 32: 362653 
  Number of connections on node 2: 70450 
  Number of synaptic contacts on node 2: 368559 
  Number of connections on node 48: 70098 
  Number of synaptic contacts on node 48: 368187 
  Number of connections on node 42: 71190 
  Number of synaptic contacts on node 42: 373335 
  Number of connections on node 107: 69866 
  Number of synaptic contacts on node 107: 366269 
  Number of connections on node 81: 71206 
  Number of synaptic contacts on node 81: 373703 
  Number of connections on node 91: 71898 
  Number of synaptic contacts on node 91: 376978 
  Number of connections on node 99: 72454 
  Number of synaptic contacts on node 99: 379264 
  Number of connections on node 56: 69380 
  Number of synaptic contacts on node 56: 361152 
  Number of connections on node 89: 70198 
  Number of synaptic contacts on node 89: 368722 
  Number of connections on node 8: 70870 
  Number of synaptic contacts on node 8: 372267 
  Number of connections on node 121: 70758 
  Number of synaptic contacts on node 121: 370382 
  Number of connections on node 123: 70373 
  Number of synaptic contacts on node 123: 369641 
  Number of connections on node 115: 68966 
  Number of synaptic contacts on node 115: 357778 
  Number of connections on node 97: 71015 
  Number of synaptic contacts on node 97: 370959 
  Number of connections on node 50: 69688 
  Number of synaptic contacts on node 50: 365161 
  Number of connections on node 58: 71046 
  Number of synaptic contacts on node 58: 371611 
  Number of connections on node 75: 70658 
  Number of synaptic contacts on node 75: 369958 
  Number of connections on node 67: 70054 
  Number of synaptic contacts on node 67: 368701 
  Number of connections on node 83: 70149 
  Number of synaptic contacts on node 83: 367963 
  Number of connections on node 34: 69571 
  Number of synaptic contacts on node 34: 364126 
  Number of connections on node 65: 69425 
  Number of synaptic contacts on node 65: 365347 
  Number of connections on node 10: 71641 
  Number of synaptic contacts on node 10: 375538 
  Number of connections on node 113: 70117 
  Number of synaptic contacts on node 113: 367101 
  Number of connections on node 105: 70180 
  Number of synaptic contacts on node 105: 368601 
  Number of connections on node 80: 69793 
  Number of synaptic contacts on node 80: 366963 
  Number of connections on node 122: 69312 
  Number of synaptic contacts on node 122: 362664 
  Number of connections on node 73: 70731 
  Number of synaptic contacts on node 73: 374290 
  Number of connections on node 90: 70534 
  Number of synaptic contacts on node 90: 369212 
  Number of connections on node 66: 70498 
  Number of synaptic contacts on node 66: 368304 
  Number of connections on node 112: 70703 
  Number of synaptic contacts on node 112: 369991 
  Number of connections on node 88: 70050 
  Number of synaptic contacts on node 88: 368983 
  Number of connections on node 104: 71277 
  Number of synaptic contacts on node 104: 372324 
  Number of connections on node 74: 69972 
  Number of synaptic contacts on node 74: 365943 
  Number of connections on node 106: 68809 
  Number of synaptic contacts on node 106: 358932 
  Number of connections on node 72: 72141 
  Number of synaptic contacts on node 72: 376974 
  Number of connections on node 120: 70797 
  Number of synaptic contacts on node 120: 370846 
  Number of connections on node 114: 69484 
  Number of synaptic contacts on node 114: 361459 
  Number of connections on node 96: 70964 
  Number of synaptic contacts on node 96: 370634 
  Number of connections on node 64: 69475 
  Number of synaptic contacts on node 64: 364794 
  Number of connections on node 98: 70498 
  Number of synaptic contacts on node 98: 370327 
  Number of connections on node 82: 69665 
  Number of synaptic contacts on node 82: 363869 
  Number of connections on node 47: 70283 
  Number of synaptic contacts on node 47: 366061 
  Number of connections on node 39: 69571 
  Number of synaptic contacts on node 39: 364650 
  Number of connections on node 23: 70880 
  Number of synaptic contacts on node 23: 374895 
  Number of connections on node 13: 68785 
  Number of synaptic contacts on node 13: 360816 
  Number of connections on node 7: 69346 
  Number of synaptic contacts on node 7: 363398 
  Number of connections on node 29: 72097 
  Number of synaptic contacts on node 29: 377876 
  Number of connections on node 5: 69196 
  Number of synaptic contacts on node 5: 362033 
  Number of connections on node 15: 71332 
  Number of synaptic contacts on node 15: 376906 
  Number of connections on node 31: 70066 
  Number of synaptic contacts on node 31: 368392 
  Number of connections on node 55: 70068 
  Number of synaptic contacts on node 55: 368633 
  Number of connections on node 53: 71948 
  Number of synaptic contacts on node 53: 375308 
  Number of connections on node 37: 70783 
  Number of synaptic contacts on node 37: 369173 
  Number of connections on node 21: 70550 
  Number of synaptic contacts on node 21: 371342 
  Number of connections on node 45: 70910 
  Number of synaptic contacts on node 45: 371699 
  Number of connections on node 22: 71689 
  Number of synaptic contacts on node 22: 376720 
  Number of connections on node 12: 69553 
  Number of synaptic contacts on node 12: 367935 
  Number of connections on node 44: 70897 
  Number of synaptic contacts on node 44: 372410 
  Number of connections on node 30: 67461 
  Number of synaptic contacts on node 30: 353714 
  Number of connections on node 60: 69489 
  Number of synaptic contacts on node 60: 362686 
  Number of connections on node 77: 69802 
  Number of synaptic contacts on node 77: 365022 
  Number of connections on node 28: 71650 
  Number of synaptic contacts on node 28: 375306 
  Number of connections on node 87: 70826 
  Number of synaptic contacts on node 87: 370425 
  Number of connections on node 52: 71632 
  Number of synaptic contacts on node 52: 375863 
  Number of connections on node 71: 70337 
  Number of synaptic contacts on node 71: 366450 
  Number of connections on node 6: 70581 
  Number of synaptic contacts on node 6: 369506 
  Number of connections on node 119: 69427 
  Number of synaptic contacts on node 119: 362738 
  Number of connections on node 62: 69949 
  Number of synaptic contacts on node 62: 365092 
  Number of connections on node 61: 68305 
  Number of synaptic contacts on node 61: 359893 
  Number of connections on node 4: 68959 
  Number of synaptic contacts on node 4: 362662 
  Number of connections on node 109: 69167 
  Number of synaptic contacts on node 109: 363199 
  Number of connections on node 117: 69862 
  Number of synaptic contacts on node 117: 367546 
  Number of connections on node 103: 70987 
  Number of synaptic contacts on node 103: 370403 
  Number of connections on node 93: 72727 
  Number of synaptic contacts on node 93: 381071 
  Number of connections on node 36: 71653 
  Number of synaptic contacts on node 36: 374252 
  Number of connections on node 38: 70111 
  Number of synaptic contacts on node 38: 366668 
  Number of connections on node 20: 73063 
  Number of synaptic contacts on node 20: 382222 
  Number of connections on node 79: 69478 
  Number of synaptic contacts on node 79: 362839 
  Number of connections on node 127: 71123 
  Number of synaptic contacts on node 127: 371213 
  Number of connections on node 125: 73164 
  Number of synaptic contacts on node 125: 382662 
  Number of connections on node 101: 70927 
  Number of synaptic contacts on node 101: 373324 
  Number of connections on node 63: 69626 
  Number of synaptic contacts on node 63: 363151 
  Number of connections on node 54: 70154 
  Number of synaptic contacts on node 54: 366773 
  Number of connections on node 111: 70860 
  Number of synaptic contacts on node 111: 369280 
  Number of connections on node 85: 68813 
  Number of synaptic contacts on node 85: 361644 
  Number of connections on node 14: 70075 
  Number of synaptic contacts on node 14: 367592 
  Number of connections on node 95: 69585 
  Number of synaptic contacts on node 95: 361661 
  Number of connections on node 46: 70126 
  Number of synaptic contacts on node 46: 368791 
  Number of connections on node 84: 68315 
  Number of synaptic contacts on node 84: 359023 
  Number of connections on node 108: 70093 
  Number of synaptic contacts on node 108: 365561 
  Number of connections on node 92: 69772 
  Number of synaptic contacts on node 92: 364599 
  Number of connections on node 68: 69667 
  Number of synaptic contacts on node 68: 361944 
  Number of connections on node 78: 71721 
  Number of synaptic contacts on node 78: 376189 
  Number of connections on node 100: 70523 
  Number of synaptic contacts on node 100: 368847 
  Number of connections on node 76: 70882 
  Number of synaptic contacts on node 76: 370652 
  Number of connections on node 102: 69277 
  Number of synaptic contacts on node 102: 361268 
  Number of connections on node 118: 69917 
  Number of synaptic contacts on node 118: 368019 
  Number of connections on node 94: 69328 
  Number of synaptic contacts on node 94: 361872 
  Number of connections on node 126: 70912 
  Number of synaptic contacts on node 126: 374373 
  Number of connections on node 86: 67431 
  Number of synaptic contacts on node 86: 354739 
  Number of connections on node 116: 70474 
  Number of synaptic contacts on node 116: 368583 
  Number of connections on node 110: 69458 
  Number of synaptic contacts on node 110: 364921 
  Number of connections on node 124: 72482 
  Number of synaptic contacts on node 124: 379133 
  Number of connections on node 70: 69133 
  Number of synaptic contacts on node 70: 360897 
  Number of connections on node 69: 71889 
  Number of synaptic contacts on node 69: 378609 
  Done; cell connection time = 7526.98 s.
Adding stims...
  Number of stims on node 0: 2603 
  Number of stims on node 10: 2603 
  Number of stims on node 9: 2603 
  Number of stims on node 7: 2603 
  Number of stims on node 56: 2583 
  Number of stims on node 97: 2603 
  Number of stims on node 73: 2583 
  Number of stims on node 23: 2583 
  Number of stims on node 24: 2583 
  Number of stims on node 88: 2582 
  Number of stims on node 48: 2583 
  Number of stims on node 33: 2583 
  Number of stims on node 81: 2582 
  Number of stims on node 41: 2583 
  Number of stims on node 57: 2583 
  Number of stims on node 1: 2603 
  Number of stims on node 58: 2583 
  Number of stims on node 49: 2583 
  Number of stims on node 18: 2603 
  Number of stims on node 72: 2583 
  Number of stims on node 96: 2603 
  Number of stims on node 65: 2583 
  Number of stims on node 80: 2582 
  Number of stims on node 74: 2582 
  Number of stims on node 66: 2583 
  Number of stims on node 90: 2582 
  Number of stims on node 40: 2583 
  Number of stims on node 89: 2582 
  Number of stims on node 16: 2603 
  Number of stims on node 98: 2603 
  Number of stims on node 64: 2583 
  Number of stims on node 2: 2603 
  Number of stims on node 17: 2603 
  Number of stims on node 112: 2603 
  Number of stims on node 26: 2583 
  Number of stims on node 106: 2603 
  Number of stims on node 82: 2582 
  Number of stims on node 114: 2593 
  Number of stims on node 34: 2583 
  Number of stims on node 32: 2583 
  Number of stims on node 8: 2603 
  Number of stims on node 3: 2603 
  Number of stims on node 11: 2603 
  Number of stims on node 95: 2603 
  Number of stims on node 122: 2593 
  Number of stims on node 25: 2583 
  Number of stims on node 37: 2583 
  Number of stims on node 42: 2583 
  Number of stims on node 43: 2583 
  Number of stims on node 35: 2583 
  Number of stims on node 83: 2582 
  Number of stims on node 29: 2583 
  Number of stims on node 27: 2583 
  Number of stims on node 21: 2583 
  Number of stims on node 47: 2583 
  Number of stims on node 75: 2582 
  Number of stims on node 50: 2583 
  Number of stims on node 127: 2593 
  Number of stims on node 86: 2582 
  Number of stims on node 119: 2593 
  Number of stims on node 76: 2582 
  Number of stims on node 79: 2582 
  Number of stims on node 104: 2603 
  Number of stims on node 123: 2593 
  Number of stims on node 59: 2583 
  Number of stims on node 4: 2603 
  Number of stims on node 120: 2593 
  Number of stims on node 19: 2603 
  Number of stims on node 67: 2583 
  Number of stims on node 105: 2603 
  Number of stims on node 113: 2603 
  Number of stims on node 60: 2583 
  Number of stims on node 100: 2603 
  Number of stims on node 71: 2583 
  Number of stims on node 121: 2593 
  Number of stims on node 22: 2583 
  Number of stims on node 103: 2603 
  Number of stims on node 52: 2583 
  Number of stims on node 51: 2583 
  Number of stims on node 77: 2582 
  Number of stims on node 99: 2603 
  Number of stims on node 13: 2603 
  Number of stims on node 118: 2593 
  Number of stims on node 39: 2583 
  Number of stims on node 63: 2583 
  Number of stims on node 55: 2583 
  Number of stims on node 111: 2603 
  Number of stims on node 87: 2582 
  Number of stims on node 53: 2583 
  Number of stims on node 28: 2583 
  Number of stims on node 14: 2603 
  Number of stims on node 84: 2582 
  Number of stims on node 91: 2582 
  Number of stims on node 44: 2583 
  Number of stims on node 15: 2603 
  Number of stims on node 31: 2583 
  Number of stims on node 6: 2603 
  Number of stims on node 36: 2583 
  Number of stims on node 116: 2593 
  Number of stims on node 109: 2603 
  Number of stims on node 94: 2603 
  Number of stims on node 85: 2582 
  Number of stims on node 20: 2583 
  Number of stims on node 107: 2603 
  Number of stims on node 12: 2603 
  Number of stims on node 117: 2593 
  Number of stims on node 69: 2583 
  Number of stims on node 45: 2583 
  Number of stims on node 92: 2582 
  Number of stims on node 68: 2583 
  Number of stims on node 93: 2582 
  Number of stims on node 38: 2583 
  Number of stims on node 5: 2603 
  Number of stims on node 78: 2582 
  Number of stims on node 125: 2593 
  Number of stims on node 46: 2583 
  Number of stims on node 115: 2593 
  Number of stims on node 62: 2583 
  Number of stims on node 54: 2583 
  Number of stims on node 110: 2603 
  Number of stims on node 70: 2583 
  Number of stims on node 30: 2583 
  Number of stims on node 61: 2583 
  Number of stims on node 102: 2603 
  Number of stims on node 126: 2593 
  Number of stims on node 101: 2603 
  Number of stims on node 108: 2603 
  Number of stims on node 124: 2593 
  Done; cell stims creation time = 8.71 s.
Recording 10 traces of 1 types on node 86
Recording 3 traces of 1 types on node 37
Recording 5 traces of 1 types on node 23
Recording 8 traces of 1 types on node 113
Recording 7 traces of 1 types on node 3
Recording 6 traces of 1 types on node 42
Recording 8 traces of 1 types on node 56
Recording 7 traces of 1 types on node 97
Recording 7 traces of 1 types on node 66
Recording 12 traces of 1 types on node 0
Recording 6 traces of 1 types on node 90
Recording 5 traces of 1 types on node 95
Recording 5 traces of 1 types on node 40
Recording 12 traces of 1 types on node 114
Recording 9 traces of 1 types on node 115
Recording 9 traces of 1 types on node 100
Recording 10 traces of 1 types on node 82
Recording 7 traces of 1 types on node 22
Recording 7 traces of 1 types on node 7
Recording 9 traces of 1 types on node 44
Recording 9 traces of 1 types on node 80
Recording 10 traces of 1 types on node 52
Recording 5 traces of 1 types on node 65
Recording 8 traces of 1 types on node 104
Recording 8 traces of 1 types on node 74
Recording 8 traces of 1 types on node 11
Recording 4 traces of 1 types on node 41
Recording 7 traces of 1 types on node 14
Recording 9 traces of 1 types on node 75
Recording 13 traces of 1 types on node 60
Recording 8 traces of 1 types on node 10
Recording 12 traces of 1 types on node 124
Recording 7 traces of 1 types on node 125
Recording 12 traces of 1 types on node 83
Recording 5 traces of 1 types on node 48
Recording 4 traces of 1 types on node 25
Recording 6 traces of 1 types on node 72
Recording 6 traces of 1 types on node 24
Recording 7 traces of 1 types on node 71
Recording 5 traces of 1 types on node 21
Recording 5 traces of 1 types on node 33
Recording 8 traces of 1 types on node 123
Recording 8 traces of 1 types on node 38
Recording 3 traces of 1 types on node 43
Recording 6 traces of 1 types on node 59
Recording 5 traces of 1 types on node 58
Recording 9 traces of 1 types on node 103
Recording 4 traces of 1 types on node 13
Recording 4 traces of 1 types on node 28
Recording 8 traces of 1 types on node 111
Recording 9 traces of 1 types on node 64
Recording 7 traces of 1 types on node 53
Recording 11 traces of 1 types on node 105
Recording 5 traces of 1 types on node 73
Recording 7 traces of 1 types on node 96
Recording 8 traces of 1 types on node 2
Recording 2 traces of 1 types on node 34
Recording 5 traces of 1 types on node 20
Recording 8 traces of 1 types on node 79
Recording 9 traces of 1 types on node 68
Recording 7 traces of 1 types on node 106
Recording 7 traces of 1 types on node 102
Recording 10 traces of 1 types on node 121
Recording 9 traces of 1 types on node 99
Recording 5 traces of 1 types on node 15
Recording 8 traces of 1 types on node 117
Recording 8 traces of 1 types on node 85
Recording 13 traces of 1 types on node 107
Recording 5 traces of 1 types on node 70
Recording 7 traces of 1 types on node 84
Recording 6 traces of 1 types on node 81
Recording 5 traces of 1 types on node 17
Recording 12 traces of 1 types on node 91
Recording 7 traces of 1 types on node 63
Recording 7 traces of 1 types on node 127
Recording 7 traces of 1 types on node 110
Recording 10 traces of 1 types on node 88
Recording 7 traces of 1 types on node 18
Recording 9 traces of 1 types on node 1
Recording 5 traces of 1 types on node 120
Recording 8 traces of 1 types on node 16
Recording 9 traces of 1 types on node 26
Recording 7 traces of 1 types on node 94
Recording 5 traces of 1 types on node 35
Recording 6 traces of 1 types on node 49
Recording 7 traces of 1 types on node 19
Recording 4 traces of 1 types on node 47
Recording 7 traces of 1 types on node 108
Recording 5 traces of 1 types on node 55
Recording 12 traces of 1 types on node 112
Recording 8 traces of 1 types on node 62
Recording 9 traces of 1 types on node 57
Recording 10 traces of 1 types on node 4
Recording 9 traces of 1 types on node 27
Recording 10 traces of 1 types on node 51
Recording 10 traces of 1 types on node 119
Recording 9 traces of 1 types on node 93
Recording 2 traces of 1 types on node 92
Recording 10 traces of 1 types on node 118
Recording 8 traces of 1 types on node 77
Recording 9 traces of 1 types on node 116
Recording 10 traces of 1 types on node 126
Recording 9 traces of 1 types on node 54
Recording 7 traces of 1 types on node 5
Recording 4 traces of 1 types on node 32
Recording 13 traces of 1 types on node 109
Recording 6 traces of 1 types on node 46
Recording 8 traces of 1 types on node 6
Recording 8 traces of 1 types on node 12
Recording 8 traces of 1 types on node 87
Recording 8 traces of 1 types on node 45
Recording 9 traces of 1 types on node 101
Recording 4 traces of 1 types on node 69
Recording 7 traces of 1 types on node 76
Recording 3 traces of 1 types on node 122
Recording 6 traces of 1 types on node 36
Recording 9 traces of 1 types on node 98
Recording 6 traces of 1 types on node 30
Recording 5 traces of 1 types on node 50
Recording 8 traces of 1 types on node 8
Recording 6 traces of 1 types on node 67
Recording 8 traces of 1 types on node 31
Recording 7 traces of 1 types on node 9
Recording 6 traces of 1 types on node 78
Recording 7 traces of 1 types on node 29
Recording 7 traces of 1 types on node 89
Recording 2 traces of 1 types on node 39
Recording 9 traces of 1 types on node 61
0.0s

Running simulation using NEURON for 12000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
2.6s
2.7s
2.8s
2.9s
3.0s
3.1s
3.2s
3.3s
3.4s
3.5s
3.6s
3.7s
3.8s
3.9s
4.0s
4.1s
4.2s
4.3s
4.4s
4.5s
4.6s
4.7s
4.8s
4.9s
5.0s
5.1s
5.2s
5.3s
5.4s
5.5s
5.6s
5.7s
5.8s
5.9s
6.0s
6.1s
6.2s
6.3s
6.4s
6.5s
6.6s
6.7s
6.8s
6.9s
7.0s
7.1s
7.2s
7.3s
7.4s
7.5s
7.6s
7.7s
7.8s
7.9s
8.0s
8.1s
8.2s
8.3s
8.4s
8.5s
8.6s
8.7s
8.8s
8.9s
9.0s
9.1s
9.2s
9.3s
9.4s
9.5s
9.6s
9.7s
9.8s
9.9s
10.0s
10.1s
10.2s
10.3s
10.4s
10.5s
10.6s
10.7s
10.8s
10.9s
11.0s
11.1s
11.2s
11.3s
11.4s
11.5s
11.6s
11.7s
11.8s
11.9s
  Done; run time = 81359.00 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 17.90 s.

Analyzing...
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15544f163d00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15544f163f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15544f163f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba672140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba672080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba672080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554979a4d40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554979a4ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554979a4ec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155440f3be00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155440f3bc80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155440f3bc80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548548e440>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548548e640>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548548e640>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e53f800>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e53fdc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e53fdc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf50e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf50f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf50f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548c570a00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548c570b80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548c570b80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b0d1500>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b0d1680>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b0d1680>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548af88d40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548af88140>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548af88140>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba809fc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba8090c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba8090c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155496fcce00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155496fcce80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155496fcce80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e348700>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e348d00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e348d00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155491d61940>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155491d61080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155491d61080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155486cb1dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155486cb1f40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155486cb1f40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacf2140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacf2040>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacf2040>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5c6dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5c6e80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5c6e80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba6a9f80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba6a9f40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba6a9f40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b0fe800>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b0fe980>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b0fe980>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba57f180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba57f080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba57f080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e8c0640>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e8c0c40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e8c0c40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e557640>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e557c40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e557c40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5c8280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5c81c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5c81c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548e463740>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548e4634c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548e4634c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b375100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b375280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b375280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba67c1c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba67c100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba67c100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5a4280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5a4340>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5a4340>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e7c3780>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e7c3d40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e7c3d40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacc9500>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacc9600>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacc9600>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548aaa9380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548aaa9500>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548aaa9500>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b64b180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b64b300>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b64b300>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba98ff00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba98f040>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba98f040>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548ac63440>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548ac635c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548ac635c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bac70640>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bac70900>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bac70900>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb5fac00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb5fac40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb5fac80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e55c680>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e55cc80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e55cc80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b090100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b090280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b090280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155318dd0c00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155318dd0fc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155318dd0fc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155498623d40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155498623100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155498623100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e520740>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e520d40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e520d40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554958273c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155495827540>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155495827540>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155481a01c00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155481a01300>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155481a01300>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b6672c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b667440>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554b93c1e40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554b93c1080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554b93c1080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554b9509440>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554b95092c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554b95092c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bace0100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bace0040>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bace0040>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548d3c3cc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548d3c3bc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548d3c3bc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e54b6c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e54be80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e54be80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155494a42500>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155494a42740>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155494a42740>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155483317c80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155483317b00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155483317b00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554badebe80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554badebf80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554badebf80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf92a80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf92b40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf92b40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b2d9600>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b2d9180>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b2d9180>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafead40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafeae00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafeae00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155497bf9240>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155497bf90c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155497bf90c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba765280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7651c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7651c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b423980>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b423200>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b423200>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba556180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba556080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba556080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548208f280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548208f480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548208f480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548aede980>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548aede200>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548aede200>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacc5940>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacc5a40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacc5a40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155471269e00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155471269240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155471269240>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad32e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad32f00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad32f00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba784e40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba784f00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba784f00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155486adf300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155486adf480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155486adf480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15547955e780>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15547955ed80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15547955ed80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b0e5100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b0e5280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b0e5280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155450a63300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155450a63080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155450a63080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b13e540>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b13e6c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b13e6c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546361b3c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546361b540>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546361b540>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e6b1640>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e6b1a40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e6b1a40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548af36180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548af36300>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548af36300>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554897a7dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554897a7e40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554897a7e40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb014c80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb014f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb014f80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba8b2d40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba8b2e00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba8b2e00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b266480>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b266600>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b266600>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba69cec0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba69cfc0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba69cfc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5aeec0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5ae080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5ae080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548afc1840>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548afc1140>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548afc1140>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba7b1380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7b12c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7b12c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba472080>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4720c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4720c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155450e1b340>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155450e1b4c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155450e1b4c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafc1e40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafc1f40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafc1f40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb000240>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb000500>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb000500>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bad03180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bad03080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bad03080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554920b0940>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacb3100>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacb3080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacb3080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b1aa200>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b1aa380>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b1aa380>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1553ed1cf200>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1553ed1cf080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1553ed1cf080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba67b300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba67b240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba67b240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b667440>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548c019180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548c019300>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548c019300>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba7d3fc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7d30c0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7d30c0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548bffb880>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548bffb500>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548bffb500>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15547162be40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15547162bec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15547162bec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b082b00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b082c80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b082c80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4ad3c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4ad480>)
Plotting spike frequency...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4c8e80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4c8080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4c8080>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bac855c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bac85280>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bac85280>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba36a300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba36a240>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba36a240>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b444680>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b444800>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b444800>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e5ce7c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e5ced80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e5ced80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba4e7140>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba4e7080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4e7080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba50ae80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba50af80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba50af80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x155486a14b80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x155486a14d00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x155486a14d00>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba50ce00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba50cec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba50cec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baf8ecc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baf8ef80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baf8ef80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e575680>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e575c80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e575c80>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548d09f280>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548d09f480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548d09f480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baff5dc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baff5ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baff5ec0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b393300>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b393480>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b393480>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554920b0ac0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554920b0ac0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bafc1cc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bafc1d80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bafc1d80>)
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554baa34bc0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554baa34c80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554baa34c80>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba4ad480>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b031a00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b031100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b031100>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba646cc0>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba65dc80>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba65dd40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba65dd40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba592e00>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba592ec0>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba592ec0>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba429180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba429080>)
Plotting spike frequency...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba646f80>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba429080>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba646f80>)
Preparing spike data...
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b05fe40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b05f040>)  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15546e645700>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bacc0f80>)

Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b05f040>)
Preparing spike data...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bacc0f40>)
Plotting spike frequency...
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15546e645d00>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15546e645d00>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba885d80>)
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bacc0f40>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba885e40>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba885e40>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba7da180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba7da080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba7da080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554bb084540>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554bb084640>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554bb084640>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba5a61c0>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba5a6100>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba5a6100>)
Preparing spike data...
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba645380>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba645080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba645080>)
Preparing spike data...
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x1554ba427180>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x1554ba427080>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x1554ba427080>)
  There was an exception in prepareSpikeData(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x15548b8df200>)
  There was an exception in prepareSpikeHist(): 
    'int' object is not subscriptable 
    (<class 'TypeError'>, TypeError("'int' object is not subscriptable"), <traceback object at 0x15548b8df380>)
Plotting spike frequency...
  There was an exception in plotSpikeFreq(): 
    local variable 'spkInds' referenced before assignment 
    (<class 'UnboundLocalError'>, UnboundLocalError("local variable 'spkInds' referenced before assignment"), <traceback object at 0x15548b8df380>)
  Cells: 33738
  Connections: 0 (0.00 per cell)
  Spikes: 1037403 (2.56 Hz)
  Simulated time: 12.0 s; 128 workers
  Run time: 81359.00 s
   L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.000 Hz
   L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   L1_HAC_cIR : 0.000 Hz
   L1_HAC_cNA : 0.000 Hz
   L1_NGC-DA_bNA : 0.000 Hz
   L1_NGC-DA_cAC : 0.000 Hz
   L1_NGC-DA_cNA : 0.000 Hz
   L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   L1_SLAC_bNA : 0.006 Hz
   L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   L23_BP_bAC : 0.639 Hz
   L23_BP_bIR : 0.646 Hz
   L23_BP_bNA : 2.917 Hz
   L23_BP_cAC : 2.190 Hz
   L23_BP_cNA : 3.958 Hz
   L23_BP_dST : 0.611 Hz
   L23_BTC_bAC : 0.044 Hz
   L23_BTC_bIR : 0.036 Hz
   L23_BTC_bNA : 0.065 Hz
   L23_BTC_cAC : 0.039 Hz
   L23_BTC_cNA : 0.060 Hz
   L23_ChC_cAC : 0.312 Hz
   L23_ChC_cNA : 0.170 Hz
   L23_ChC_dNA : 0.106 Hz
   L23_DBC_bAC : 0.368 Hz
   L23_DBC_bIR : 0.070 Hz
   L23_DBC_bNA : 0.246 Hz
   L23_DBC_cAC : 0.231 Hz
   L23_LBC_bAC : 0.033 Hz
   L23_LBC_bNA : 0.602 Hz
   L23_LBC_cAC : 0.066 Hz
   L23_LBC_cNA : 0.076 Hz
   L23_LBC_cST : 0.223 Hz
   L23_LBC_dNA : 0.355 Hz
   L23_MC_bAC : 0.008 Hz
   L23_MC_bNA : 0.017 Hz
   L23_MC_cAC : 0.023 Hz
   L23_MC_cNA : 0.028 Hz
   L23_MC_dNA : 0.008 Hz
   L23_NBC_bAC : 0.030 Hz
   L23_NBC_bNA : 0.222 Hz
   L23_NBC_cAC : 0.049 Hz
   L23_NBC_cIR : 0.000 Hz
   L23_NBC_cNA : 0.056 Hz
   L23_NBC_dNA : 0.129 Hz
   L23_NGC_bNA : 0.133 Hz
   L23_NGC_cAC : 0.100 Hz
   L23_NGC_cNA : 0.100 Hz
   L23_NGC_cST : 0.067 Hz
   L23_PC_cAD : 0.335 Hz
   L23_SBC_bNA : 0.414 Hz
   L23_SBC_cAC : 0.547 Hz
   L23_SBC_dNA : 0.190 Hz
   L4_BP_bAC : 8.417 Hz
   L4_BP_bIR : 5.917 Hz
   L4_BP_bNA : 5.542 Hz
   L4_BP_cAC : 5.083 Hz
   L4_BP_cNA : 11.417 Hz
   L4_BP_dST : 0.083 Hz
   L4_BTC_bAC : 4.250 Hz
   L4_BTC_bIR : 0.042 Hz
   L4_BTC_bST : 0.125 Hz
   L4_BTC_cAC : 0.343 Hz
   L4_BTC_cNA : 0.083 Hz
   L4_BTC_dNA : 0.208 Hz
   L4_ChC_cAC : 6.833 Hz
   L4_ChC_cNA : 1.806 Hz
   L4_ChC_dNA : 0.458 Hz
   L4_DBC_bAC : 5.396 Hz
   L4_DBC_bIR : 0.077 Hz
   L4_DBC_bNA : 0.354 Hz
   L4_DBC_bST : 0.083 Hz
   L4_DBC_cAC : 0.271 Hz
   L4_DBC_cIR : 0.060 Hz
   L4_DBC_cNA : 0.146 Hz
   L4_LBC_cAC : 2.549 Hz
   L4_LBC_cNA : 2.619 Hz
   L4_LBC_cST : 1.750 Hz
   L4_LBC_dNA : 4.036 Hz
   L4_LBC_dST : 1.259 Hz
   L4_MC_bAC : 0.008 Hz
   L4_MC_bNA : 0.000 Hz
   L4_MC_cAC : 0.038 Hz
   L4_MC_cNA : 0.032 Hz
   L4_MC_dNA : 0.000 Hz
   L4_NBC_cAC : 3.758 Hz
   L4_NBC_cIR : 0.400 Hz
   L4_NBC_cNA : 2.483 Hz
   L4_NBC_dNA : 2.079 Hz
   L4_NGC_bNA : 0.417 Hz
   L4_NGC_cAC : 0.667 Hz
   L4_NGC_cNA : 0.389 Hz
   L4_NGC_cST : 0.083 Hz
   L4_PC_cAD : 1.489 Hz
   L4_SBC_bNA : 6.103 Hz
   L4_SBC_cAC : 5.583 Hz
   L4_SBC_dNA : 5.059 Hz
   L4_SP_cAD : 2.849 Hz
   L4_SS_cAD : 3.150 Hz
   L5_BP_bAC : 4.472 Hz
   L5_BP_bIR : 0.200 Hz
   L5_BP_bNA : 8.231 Hz
   L5_BP_cAC : 10.324 Hz
   L5_BP_cNA : 14.067 Hz
   L5_BP_dST : 0.194 Hz
   L5_BTC_bAC : 5.583 Hz
   L5_BTC_cAC : 1.463 Hz
   L5_BTC_cNA : 1.750 Hz
   L5_ChC_cAC : 15.679 Hz
   L5_ChC_cNA : 19.940 Hz
   L5_ChC_dNA : 8.750 Hz
   L5_DBC_bAC : 3.574 Hz
   L5_DBC_bIR : 0.083 Hz
   L5_DBC_bNA : 0.648 Hz
   L5_DBC_bST : 0.157 Hz
   L5_DBC_cAC : 1.093 Hz
   L5_DBC_cIR : 0.137 Hz
   L5_DBC_cNA : 1.167 Hz
   L5_LBC_bAC : 6.111 Hz
   L5_LBC_cAC : 10.087 Hz
   L5_LBC_cIR : 1.506 Hz
   L5_LBC_cNA : 18.212 Hz
   L5_LBC_cST : 11.459 Hz
   L5_LBC_dNA : 19.309 Hz
   L5_LBC_dST : 8.857 Hz
   L5_MC_bAC : 0.370 Hz
   L5_MC_bIR : 0.076 Hz
   L5_MC_bST : 0.068 Hz
   L5_MC_cAC : 0.774 Hz
   L5_MC_cNA : 0.234 Hz
   L5_MC_cST : 0.057 Hz
   L5_MC_dNA : 0.073 Hz
   L5_NBC_bAC : 4.196 Hz
   L5_NBC_bIR : 0.786 Hz
   L5_NBC_bST : 3.892 Hz
   L5_NBC_cAC : 12.990 Hz
   L5_NBC_cIR : 4.440 Hz
   L5_NBC_cNA : 18.429 Hz
   L5_NBC_cST : 6.823 Hz
   L5_NBC_dST : 7.917 Hz
   L5_NGC_bNA : 7.250 Hz
   L5_NGC_cAC : 10.167 Hz
   L5_NGC_cNA : 13.700 Hz
   L5_NGC_cST : 0.167 Hz
   L5_SBC_bNA : 6.333 Hz
   L5_SBC_cAC : 10.370 Hz
   L5_SBC_dNA : 14.726 Hz
   L5_STPC_cAD : 4.267 Hz
   L5_TTPC1_cAD : 3.417 Hz
   L5_TTPC2_cAD : 3.623 Hz
   L5_UTPC_cAD : 5.923 Hz
   L6_BPC_cAD : 1.956 Hz
   L6_BP_bAC : 2.514 Hz
   L6_BP_bIR : 0.117 Hz
   L6_BP_bNA : 5.526 Hz
   L6_BP_cAC : 7.202 Hz
   L6_BP_cNA : 7.458 Hz
   L6_BP_dST : 0.083 Hz
   L6_BTC_bAC : 3.658 Hz
   L6_BTC_cAC : 3.074 Hz
   L6_BTC_cNA : 2.700 Hz
   L6_ChC_cAC : 12.028 Hz
   L6_ChC_cNA : 27.347 Hz
   L6_ChC_dNA : 10.042 Hz
   L6_DBC_bAC : 5.806 Hz
   L6_DBC_bIR : 0.083 Hz
   L6_DBC_bNA : 0.583 Hz
   L6_DBC_bST : 0.056 Hz
   L6_DBC_cAC : 4.500 Hz
   L6_DBC_cIR : 0.194 Hz
   L6_DBC_cNA : 0.694 Hz
   L6_IPC_cAD : 2.647 Hz
   L6_LBC_bAC : 4.609 Hz
   L6_LBC_bIR : 1.015 Hz
   L6_LBC_bNA : 22.360 Hz
   L6_LBC_bST : 5.986 Hz
   L6_LBC_cNA : 22.883 Hz
   L6_LBC_cST : 6.413 Hz
   L6_MC_bAC : 0.028 Hz
   L6_MC_bIR : 0.007 Hz
   L6_MC_bNA : 0.054 Hz
   L6_MC_bST : 0.012 Hz
   L6_MC_cAC : 0.076 Hz
   L6_MC_cIR : 0.018 Hz
   L6_MC_cNA : 0.089 Hz
   L6_NBC_bAC : 4.554 Hz
   L6_NBC_bIR : 1.220 Hz
   L6_NBC_bST : 7.519 Hz
   L6_NBC_cAC : 8.684 Hz
   L6_NBC_cIR : 2.310 Hz
   L6_NBC_cNA : 18.182 Hz
   L6_NBC_cST : 10.481 Hz
   L6_NBC_dST : 11.101 Hz
   L6_NGC_bNA : 5.208 Hz
   L6_NGC_cAC : 8.250 Hz
   L6_NGC_cNA : 9.159 Hz
   L6_NGC_cST : 0.167 Hz
   L6_SBC_bNA : 13.684 Hz
   L6_SBC_cAC : 14.722 Hz
   L6_SBC_dNA : 8.561 Hz
   L6_TPC_L1_cAD : 2.416 Hz
   L6_TPC_L4_cAD : 3.205 Hz
   L6_UTPC_cAD : 3.423 Hz
   ss_RTN_m : 11.405 Hz
   VPM_sTC : 2.885 Hz
   VPM_TC : 2.756 Hz
Saving output as ../data/v8_batch1/v8_batch1_0_0_data.pkl ... 
Finished saving!
  Done; saving time = 69.89 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... cell
  Done; plotting time = 231.83 s

Total time = 89383.36 s
Preparing spike data...
Plotting spike frequency...
